<?php
namespace Database\Seeders;

use App\Models\Responden;
use Illuminate\Database\Seeder;

class RespondenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Responden::insert(

            [
                [
                    'title'               => 'mrs',
                    'fullname'            => 'fauziah maryani',
                    'jabatan'             => 'staf kemendikdasmen',
                    'instansi'            => 'direktorat smk kemendikdasmen',
                    'email'               => 'fauziah.yani@pusdatin.belajar.id',
                    'phone_responden'     => '08118802676',
                    'nama_dosen_pengusul' => 'linda ika mayasari',
                    'phone_dosen'         => '08111990666',
                    'fakultas'            => 'fip',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'yasir riady',
                    'jabatan'             => 'direktur universitas terbuka medan',
                    'instansi'            => 'universitas terbuka',
                    'email'               => 'yasir.riady@gmail.com',
                    'phone_responden'     => '081808332512',
                    'nama_dosen_pengusul' => 'imas wahyu agustina',
                    'phone_dosen'         => '085691470709',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'imam santosa',
                    'jabatan'             => 'kaprodi universitas esa unggul, jakarta',
                    'instansi'            => 'universitas esa unggul, jakarta',
                    'email'               => 'imam.santosa@esaunggul.ac.id',
                    'phone_responden'     => '089637390010',
                    'nama_dosen_pengusul' => 'imas wahyu agustina',
                    'phone_dosen'         => '085691470709',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'juliana margareta sumilat',
                    'jabatan'             => 'dosen prodi pendidikan guru sd',
                    'instansi'            => 'universitas negeri manado',
                    'email'               => 'julianasumilat@unima.ac.id',
                    'phone_responden'     => '085299756289',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'aldjon n. dapa',
                    'jabatan'             => 'kajur pendidikan khusus',
                    'instansi'            => 'universitas negeri manado',
                    'email'               => 'aldjondapa@unima.ac.id',
                    'phone_responden'     => '085240838100',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'richard h. d. pangkey',
                    'jabatan'             => 'kaprodi pendidikan guru sd',
                    'instansi'            => 'universitas negeri manado',
                    'email'               => 'richardpangkey@unima.ac.id',
                    'phone_responden'     => '085256218007',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'fransiskus royke seke',
                    'jabatan'             => 'sekjur pendidikan teknik elektro',
                    'instansi'            => 'universitas negeri manado',
                    'email'               => 'fransiskusroykeseke@unima.ac.id',
                    'phone_responden'     => '081243000404',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'muhammad yusha firdaus',
                    'jabatan'             => 'perekayasa ahli pertama',
                    'instansi'            => 'brin',
                    'email'               => 'muha201@brin.go.id',
                    'phone_responden'     => '085890613124',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'mahpudin',
                    'jabatan'             => 'dosen / kaprodi pgsd',
                    'instansi'            => 'universitas majalengka',
                    'email'               => 'mahpudin893@gmail.com',
                    'phone_responden'     => '085710422322',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'bambang setiawan',
                    'jabatan'             => 'sekretaris prodi bimbingan dan konseling islam',
                    'instansi'            => 'uin siber syekh nurjati cirebon',
                    'email'               => 'bambang.setiawan@uinssc.ac.id',
                    'phone_responden'     => '082316031146',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'tito handoko',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas riau',
                    'email'               => 'tito.handoko@lecturer.unri.ac.id',
                    'phone_responden'     => '081365142852',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'tika mutia',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas islam negeri sultan syarif kasim riau',
                    'email'               => 'tikamutia@uin-suska.ac.id',
                    'phone_responden'     => '081371065600',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'sendi fauzigiwangsa',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas pendidikan indonesia',
                    'email'               => 'sendifauzigiwangsa@upi.edu',
                    'phone_responden'     => '085220161967',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'eka yuliana',
                    'jabatan'             => 'guru',
                    'instansi'            => 'sd n cipayung 07 bogor',
                    'email'               => 'cie.keukeuh77@gmail.com',
                    'phone_responden'     => '0895377177123',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'agus nugraha',
                    'jabatan'             => 'guru / wakil kepala sekolah',
                    'instansi'            => 'sekolah dasar islam',
                    'email'               => 'aggusnugraha@gmail.com',
                    'phone_responden'     => '081807908838',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'heni fatmawati',
                    'jabatan'             => 'guru',
                    'instansi'            => 'sman 7 balikpapan',
                    'email'               => 'fatmawatiheni864@gmail.com',
                    'phone_responden'     => '085247061047',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'nunung widianingsih',
                    'jabatan'             => 'guru',
                    'instansi'            => 'smkn 31 jakarta',
                    'email'               => 'widianingsihnunung3131@gmail.com',
                    'phone_responden'     => '081288848432',
                    'nama_dosen_pengusul' => 'ahmad rifqy ash-shiddiqy',
                    'phone_dosen'         => '085659256730',
                    'fakultas'            => 'fip',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'rangga firdaus',
                    'jabatan'             => 'koorprodi s2 tp fkip  unila',
                    'instansi'            => 'universitas lampung (unila)',
                    'email'               => 'ranggafirdaus@fkip.unila.ac.id',
                    'phone_responden'     => '081379006544',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'dirgantara wicaksono',
                    'jabatan'             => 'kepala unit kendali sekolah pasca sarjana umj',
                    'instansi'            => 'universitas muhammadiyah jakarta (umj)',
                    'email'               => 'bombomdirgantara@gmail.com',
                    'phone_responden'     => '08561496490',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'dwi prasetyo',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas nusa cendana (undana)',
                    'email'               => 'dpras.ilkom.undana@gmail.com',
                    'phone_responden'     => '081234713451',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'yamanto isa',
                    'jabatan'             => 'wakil direktur pascasarjana universitas batu raja',
                    'instansi'            => 'universitas batu raja',
                    'email'               => 'yamantoisa12@gmail.com',
                    'phone_responden'     => '081373711266',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'etis sunandi',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas bengkulu',
                    'email'               => 'esunandi@unib.ac.id',
                    'phone_responden'     => '81295949261',
                    'nama_dosen_pengusul' => 'siti rohmah rohimah',
                    'phone_dosen'         => '87884927201',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'acim',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas patimura',
                    'email'               => 'acim1805@gmail.com',
                    'phone_responden'     => '081280796234',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'erna retna safitri',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas sriwijaya',
                    'email'               => 'ernaretnas27@gmail.com',
                    'phone_responden'     => '08121419295',
                    'nama_dosen_pengusul' => 'hartini nara',
                    'phone_dosen'         => '081318939745',
                    'fakultas'            => 'fip',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'siti jubaidah',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas negeri jakarta',
                    'email'               => 'siti.jubaidah@unj.ac.id',
                    'phone_responden'     => '81584895930',
                    'nama_dosen_pengusul' => '',
                    'phone_dosen'         => '81584895930',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'princen',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas pelita harapan',
                    'email'               => 'princen.fpsi@uph.edu',
                    'phone_responden'     => '0819-7740-1055',
                    'nama_dosen_pengusul' => 'novitasari r. damanik',
                    'phone_dosen'         => '081388915610',
                    'fakultas'            => 'fpsi',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'muhammd afif alhad',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas brawijaya',
                    'email'               => 'afifalhad@ub.ac.id',
                    'phone_responden'     => '0852-2997-0577',
                    'nama_dosen_pengusul' => 'novitasari r. damanik',
                    'phone_dosen'         => '081388915610',
                    'fakultas'            => 'fpsi',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'ms.',
                    'fullname'            => 'tetty sinambela',
                    'jabatan'             => 'pengantar kerja',
                    'instansi'            => 'balai pelatihan vokasi dan produktivitas (bpvp) samarinda',
                    'email'               => 'tettyseptina@gmail.com',
                    'phone_responden'     => '0819-7246-191',
                    'nama_dosen_pengusul' => 'novitasari r. damanik',
                    'phone_dosen'         => '081388915610',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'ms.',
                    'fullname'            => 'rismaya saragih',
                    'jabatan'             => 'analis jabatan',
                    'instansi'            => 'badan kepegawaian dan pengembangan sumber daya manusia kabupaten deli serdang',
                    'email'               => 'rismayasaragih@gmail.com',
                    'phone_responden'     => '0817-0329-6444',
                    'nama_dosen_pengusul' => 'novitasari r. damanik',
                    'phone_dosen'         => '081388915610',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'ms.',
                    'fullname'            => 'indah rasulita sebayang',
                    'jabatan'             => 'recruitment sr. assistant manager',
                    'instansi'            => 'm.p. evans group plc',
                    'email'               => 'indahhsebayang@gmail.com',
                    'phone_responden'     => 'by request privately (not open for public)',
                    'nama_dosen_pengusul' => 'novitasari r. damanik',
                    'phone_dosen'         => '081388915610',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'ms.',
                    'fullname'            => 'delvia idola',
                    'jabatan'             => 'hr consultant',
                    'instansi'            => 'netika indonesia',
                    'email'               => 'delviaidola@gmail.com',
                    'phone_responden'     => '82268105752',
                    'nama_dosen_pengusul' => 'anggi mayangsari',
                    'phone_dosen'         => '87766608233',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'ms.',
                    'fullname'            => 'rahma dilla arnanda',
                    'jabatan'             => 'senior human capital specialist',
                    'instansi'            => 'gmf aeroasia',
                    'email'               => 'dillaarnanda2018@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'anggi mayangsari',
                    'phone_dosen'         => '87766608233',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'maria hidayati',
                    'jabatan'             => 'ketua bidang monitoring, evaluasi dan audit mutu internal, badan penjaminan mutu um',
                    'instansi'            => 'universitas negeri malang',
                    'email'               => 'maria.hidayati.fs@um.ac.id',
                    'phone_responden'     => '0813-3465-0089',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'ms.',
                    'fullname'            => 'destina wahyu winarti',
                    'jabatan'             => 'lecturer at the faculty of education',
                    'instansi'            => 'universitas islam internasional indonesia',
                    'email'               => 'destina.winarti@uiii.ac.id',
                    'phone_responden'     => '0821-4043-4760',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'indah wahyu puji utami, ph.d.',
                    'jabatan'             => 'ketua departemen sejarah, fakultas ilmu sosial',
                    'instansi'            => 'universitas negeri malang',
                    'email'               => 'indahwahyu.p.u@um.ac.id',
                    'phone_responden'     => '0812-3085-9821',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'shintia revina',
                    'jabatan'             => 'postdoctoral researcher',
                    'instansi'            => 'university of twente',
                    'email'               => 'srevina.santosa@gmail.com',
                    'phone_responden'     => '31627294002',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'lili mutiary',
                    'jabatan'             => 'kepala subbagian pengelolaan risiko dan kinerja',
                    'instansi'            => 'kemenkeu',
                    'email'               => 'lili.mutiary@gmail.com',
                    'phone_responden'     => '(not open for public)',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'al jupri',
                    'jabatan'             => 'professor/head of mathematics study program',
                    'instansi'            => 'universitas pendidikan indonesia',
                    'email'               => 'aljupri@upi.edu',
                    'phone_responden'     => '6281223900483',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'dr. anita dewi utami, m. pd.',
                    'jabatan'             => 'dosen s1 pendidikan matematika',
                    'instansi'            => 'universitas negeri malang',
                    'email'               => 'anita.dewiutami.fmipa@um.ac.id',
                    'phone_responden'     => '82232877941',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'dr. muhammad iqbal, s.pd., m.pd',
                    'jabatan'             => 'dosen pendidikan olahraga fkip',
                    'instansi'            => 'universitas syiah kuala',
                    'email'               => 'iqbal_3377@yahoo.com',
                    'phone_responden'     => '85260003377',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'dewi annisa',
                    'jabatan'             => 'dosen pendidikan matematika fkip',
                    'instansi'            => 'universitas syiah kuala',
                    'email'               => 'dewiannisa@usk.ac.id',
                    'phone_responden'     => '81360458837',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'dedi suryadi, m.ed, ph.d',
                    'jabatan'             => 'wadek akademik fpb umy',
                    'instansi'            => 'universitas muhammadiyah yogyakarta(umy)',
                    'email'               => 'dedisuryadi@umy.ac.id',
                    'phone_responden'     => '81394119980',
                    'nama_dosen_pengusul' => 'poppy rahayu',
                    'phone_dosen'         => '62 813-1935-4858',
                    'fakultas'            => 'fpbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'ms.',
                    'fullname'            => 'bagus wahyu jatmiko',
                    'jabatan'             => 'organizational development advisor',
                    'instansi'            => 'pt. smartfren telecom tbk',
                    'email'               => 'bagus.wahyu.j@gmail.com',
                    'phone_responden'     => '87876989175',
                    'nama_dosen_pengusul' => 'anggi mayangsari',
                    'phone_dosen'         => '87766608233',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'rahmat sagara',
                    'jabatan'             => 'peneliti',
                    'instansi'            => 'the oxford university clinical research unit (oucru) indonesia',
                    'email'               => 'rsagara@oucru.org',
                    'phone_responden'     => '8993343388',
                    'nama_dosen_pengusul' => 'siti rohmah rohimah',
                    'phone_dosen'         => '87884927201',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'santi utami dewi',
                    'jabatan'             => 'penyuluh sosial ahli muda',
                    'instansi'            => 'kementerian sosial ri',
                    'email'               => 'santi_ud@yahoo.com',
                    'phone_responden'     => '81310052702',
                    'nama_dosen_pengusul' => 'siti rohmah rohimah',
                    'phone_dosen'         => '87884927201',
                    'fakultas'            => 'fmipa',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'maulana iskak',
                    'jabatan'             => 'ce premium dan pai',
                    'instansi'            => 'erlangga',
                    'email'               => 'maul.erlangga2010@gmail.com',
                    'phone_responden'     => '85702030445',
                    'nama_dosen_pengusul' => 'siti rohmah rohimah',
                    'phone_dosen'         => '87884927201',
                    'fakultas'            => 'fmipa',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'mochamad agung prasetyo sukanto',
                    'jabatan'             => 'staff quality management',
                    'instansi'            => 'pt adhi karya (persero) tbk.',
                    'email'               => 'mochamad.sukanto@adhi.co.id',
                    'phone_responden'     => '62 813-1068-7209',
                    'nama_dosen_pengusul' => 'dr. m. agphin ramadhan, m.pd',
                    'phone_dosen'         => '8978977969',
                    'fakultas'            => 'ft',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'hans dermawan, s.pd.,m.t',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas kristen krida wacana',
                    'email'               => 'hans.dermawan@ukrida.ac.id',
                    'phone_responden'     => '62 813-8731-3735',
                    'nama_dosen_pengusul' => 'dr. m. agphin ramadhan, m.pd',
                    'phone_dosen'         => '8978977969',
                    'fakultas'            => 'ft',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'marwanto adi nugroho',
                    'jabatan'             => 'staf',
                    'instansi'            => 'universitas krisnadwipayana',
                    'email'               => 'toyamadden90@gmail.com',
                    'phone_responden'     => '62 852-1886-5110',
                    'nama_dosen_pengusul' => 'dr. m. agphin ramadhan, m.pd',
                    'phone_dosen'         => '8978977969',
                    'fakultas'            => 'ft',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'dr. ari dwi agus sulistyo',
                    'jabatan'             => 'guru',
                    'instansi'            => 'smpn12 satap menukung',
                    'email'               => 'ari.dast86@gmail.com',
                    'phone_responden'     => '62 856-4363-7609',
                    'nama_dosen_pengusul' => 'dr. m. agphin ramadhan, m.pd',
                    'phone_dosen'         => '8978977969',
                    'fakultas'            => 'ft',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'surya tangguh sentosa',
                    'jabatan'             => 'staf',
                    'instansi'            => 'pt. modern widya tehnical',
                    'email'               => 'tangguh.surya16@gmail.com',
                    'phone_responden'     => '62 896-0577-9286',
                    'nama_dosen_pengusul' => 'dr. m. agphin ramadhan, m.pd',
                    'phone_dosen'         => '8978977969',
                    'fakultas'            => 'ft',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'parlin tambunan, m.pd',
                    'jabatan'             => 'widyaiswara',
                    'instansi'            => 'bpsdm kementerian pupr',
                    'email'               => 'parlintambunan0@gmail.com',
                    'phone_responden'     => '62 812-8171-1659',
                    'nama_dosen_pengusul' => 'dr. m. agphin ramadhan, m.pd',
                    'phone_dosen'         => '8978977969',
                    'fakultas'            => 'ft',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'radinal fadli, m.pd.t',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas muhammadiyah muara bungo',
                    'email'               => 'fadliradinal@gmail.com',
                    'phone_responden'     => '62 853-6300-6848',
                    'nama_dosen_pengusul' => 'dr. m. agphin ramadhan, m.pd',
                    'phone_dosen'         => '8978977969',
                    'fakultas'            => 'ft',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'setiadi wira buana',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'institut teknologi sumatera',
                    'email'               => 'setiadi.wira@tse.itera.ac.id',
                    'phone_responden'     => '62 856-5886-8016',
                    'nama_dosen_pengusul' => 'dr. m. agphin ramadhan, m.pd',
                    'phone_dosen'         => '8978977969',
                    'fakultas'            => 'ft',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'hendry anjar purwanto, s.pd',
                    'jabatan'             => 'technical training section head',
                    'instansi'            => 'pt. wahana duta jaya rucika',
                    'email'               => 'hendry.purwanto@rucika.co.id',
                    'phone_responden'     => '62 818-0833-0109',
                    'nama_dosen_pengusul' => 'dr. m. agphin ramadhan, m.pd',
                    'phone_dosen'         => '8978977969',
                    'fakultas'            => 'ft',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'lathiful anwar, s.si, m.sc, ph.d',
                    'jabatan'             => 'head of mathematics department, faculty of mathematics and natural sciences',
                    'instansi'            => 'universitas negeri malang',
                    'email'               => 'lathiful.anwar.fmipa@um.ac.id',
                    'phone_responden'     => '6282142826826',
                    'nama_dosen_pengusul' => 'puspita sari',
                    'phone_dosen'         => '0812-1229-9297',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'byarbreda mahaputra, s.psi., mm',
                    'jabatan'             => 'manager of learning program & strategy learning',
                    'instansi'            => 'pt. amartha mikro fintek',
                    'email'               => 'byarbreda.mahaputra@amartha.com',
                    'phone_responden'     => '62 82-111-5-888-946',
                    'nama_dosen_pengusul' => 'sri juwita kusumawardhani',
                    'phone_dosen'         => '0812-21-601-37',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'ms',
                    'fullname'            => 'lathifah hanum, m.psi., psikolog',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas indonesia',
                    'email'               => 'lathifah.hanum08@ui.ac.id',
                    'phone_responden'     => '61 451-710-263',
                    'nama_dosen_pengusul' => 'sri juwita kusumawardhani',
                    'phone_dosen'         => '0812-21-601-37',
                    'fakultas'            => 'fpsi',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'dr. titi sahidah fitriana, m.psi., psikolog',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas yarsi',
                    'email'               => 'titi.sahidah36@gmail.com',
                    'phone_responden'     => '62 89-79-530-642',
                    'nama_dosen_pengusul' => 'sri juwita kusumawardhani',
                    'phone_dosen'         => '0812-21-601-37',
                    'fakultas'            => 'fpsi',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'ms',
                    'fullname'            => 'vivi, m.psi., psikolog',
                    'jabatan'             => 'direktur operasional',
                    'instansi'            => 'pt. kalea psikologi indonesia',
                    'email'               => 'vivi@kalea.id',
                    'phone_responden'     => '081-925-70-676',
                    'nama_dosen_pengusul' => 'sri juwita kusumawardhani',
                    'phone_dosen'         => '0812-21-601-37',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'ranti nurtikasari, s.si, m.pd',
                    'jabatan'             => 'head of academic performance and biology teacher',
                    'instansi'            => 'nizamia high school',
                    'email'               => 'tinkran87@gmail.com',
                    'phone_responden'     => '081-32-114-6145',
                    'nama_dosen_pengusul' => 'sri juwita kusumawardhani',
                    'phone_dosen'         => '0812-21-601-37',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'dwi cahyani setiawan',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'unika musi charitas palembang',
                    'email'               => 'dwicahyani88@gmail.com',
                    'phone_responden'     => '62 878-5217-7175',
                    'nama_dosen_pengusul' => 'adhissa qonita',
                    'phone_dosen'         => '085758600660',
                    'fakultas'            => 'fpsi',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'diana putri a',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'unika musi charitas palembang',
                    'email'               => 'dianaputriarini@gmail.com',
                    'phone_responden'     => '62 857-6481-5349',
                    'nama_dosen_pengusul' => 'adhissa qonita',
                    'phone_dosen'         => '085758600660',
                    'fakultas'            => 'fpsi',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'fitantina umar',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas muhamadiyah palembang',
                    'email'               => 'fitantina1@gmail.com',
                    'phone_responden'     => '62 813-6871-9377',
                    'nama_dosen_pengusul' => 'adhissa qonita',
                    'phone_dosen'         => '085758600660',
                    'fakultas'            => 'fpsi',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'syardian tasyabihamdika',
                    'jabatan'             => 'hr operation support',
                    'instansi'            => 'pt. infomedia nusantara',
                    'email'               => 'syardian@gmail.com',
                    'phone_responden'     => ';081288748799',
                    'nama_dosen_pengusul' => 'adhissa qonita',
                    'phone_dosen'         => '085758600660',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'ms',
                    'fullname'            => 'dr. bernadette santosa, ss, ma',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas kristen maranatha',
                    'email'               => 'bernadette.santosa@gmail.com',
                    'phone_responden'     => '81321310937',
                    'nama_dosen_pengusul' => 'dr.li. rizdika mardiana, m.pd.',
                    'phone_dosen'         => '8161965528',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'wawat srinawati, s.pd., m.pd',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas muhammadiyah bogor raya',
                    'email'               => 'wawatsrinawati@gmail.com',
                    'phone_responden'     => '6282132964587',
                    'nama_dosen_pengusul' => 'dr. li. rizdika mardiana, m.pd.',
                    'phone_dosen'         => '8161965528',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => '',
                    'fullname'            => 'putri widyastuti',
                    'jabatan'             => 'guru smp',
                    'instansi'            => 'smp islam tugasku pulomas jakarta',
                    'email'               => 'putriwidy79@gmail.com',
                    'phone_responden'     => '8128872281',
                    'nama_dosen_pengusul' => 'dr. li. rizdika mardiana, m.pd.',
                    'phone_dosen'         => '8161965528',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'prof julio cruz',
                    'jabatan'             => 'professor',
                    'instansi'            => 'universidad tecnológica de la selva (utselva), chiapas, mexico',
                    'email'               => 'arevalo.julio@laselva.edu.mx',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'dalia sukmawati',
                    'phone_dosen'         => '81316218709',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'dr liliana aguilar-marcelino',
                    'jabatan'             => 'lecturer',
                    'instansi'            => 'university of the state of morelos',
                    'email'               => 'liliana@colpos.mx',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'dalia sukmawati',
                    'phone_dosen'         => '81316218709',
                    'fakultas'            => 'fmipa',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'alo karyati, m. pd.',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas pakuan',
                    'email'               => 'alo.karyati@unpak.ac.id',
                    'phone_responden'     => '8151620364',
                    'nama_dosen_pengusul' => 'nur saadah fitri asih',
                    'phone_dosen'         => '82219150112',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'dr. dadan robihim',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'unsada',
                    'email'               => 'dadanrobihim@gmail.com',
                    'phone_responden'     => '82111768909',
                    'nama_dosen_pengusul' => 'nur saadah fitri asih',
                    'phone_dosen'         => '82219150112',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'fenny febrianty, m. pd.',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'unikom',
                    'email'               => 'fenny.febrianty@email.unikom.ac.id',
                    'phone_responden'     => '82121822503',
                    'nama_dosen_pengusul' => 'nur saadah fitri asih',
                    'phone_dosen'         => '82219150112',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'dr. juju juangsih, m. pd.',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas pendidikan indonesia',
                    'email'               => 'jujujuangsih@upi.edu',
                    'phone_responden'     => '8112005506',
                    'nama_dosen_pengusul' => 'nur saadah fitri asih',
                    'phone_dosen'         => '82219150112',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'dr. h. sobri, m. pd.',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas sultan ageng tirtayasa',
                    'email'               => 'sobri@untirta.ac.id',
                    'phone_responden'     => '8128345480',
                    'nama_dosen_pengusul' => 'nur saadah fitri asih',
                    'phone_dosen'         => '82219150112',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'galis remina babay, s. pd.',
                    'jabatan'             => 'kepala sekolah',
                    'instansi'            => 'paud little singa learning pod bekasi',
                    'email'               => 'galis.menulis@gmail.com',
                    'phone_responden'     => '85777996637',
                    'nama_dosen_pengusul' => 'nur saadah fitri asih',
                    'phone_dosen'         => '82219150112',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'rhino mantovani, s. pd.',
                    'jabatan'             => 'guru',
                    'instansi'            => 'smk negeri 2 kota depok',
                    'email'               => 'rhinomantovani@gmail.com',
                    'phone_responden'     => '85775309059',
                    'nama_dosen_pengusul' => 'nur saadah fitri asih',
                    'phone_dosen'         => '82219150112',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'irgi hadi abdail umam, s. pd.',
                    'jabatan'             => 'general manager',
                    'instansi'            => 'one creatives indonesia',
                    'email'               => 'irgi@onecreativesindonesia.com',
                    'phone_responden'     => '0 83805785398',
                    'nama_dosen_pengusul' => 'nur saadah fitri asih',
                    'phone_dosen'         => '82219150112',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'kusy k. bansae, m.a.',
                    'jabatan'             => 'district officer',
                    'instansi'            => 'yayasan ipas indonesia',
                    'email'               => 'kusykabansae@gmail.com',
                    'phone_responden'     => '85239044331',
                    'nama_dosen_pengusul' => 'reny rustyawati',
                    'phone_dosen'         => '85241890087',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'laode surazal qalbi, m.a.',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas halu oleo',
                    'email'               => 'surazal40@gmail.com',
                    'phone_responden'     => '85241581992',
                    'nama_dosen_pengusul' => 'reny rustyawati',
                    'phone_dosen'         => '85241890087',
                    'fakultas'            => 'fpsi',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'putri nabhani nurany, s.kesos., m.a.',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'uin sunan gunung djati bandung',
                    'email'               => 'putrinabhani@uinsgd.ac.id',
                    'phone_responden'     => '85838748894',
                    'nama_dosen_pengusul' => 'reny rustyawati',
                    'phone_dosen'         => '85241890087',
                    'fakultas'            => 'fpsi',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'sri hardyanti, m.a.',
                    'jabatan'             => 'instructional designer project manager',
                    'instansi'            => 'institute life management science - kpi institute',
                    'email'               => 'srihardyantibackup@gmail.com',
                    'phone_responden'     => '89679846880',
                    'nama_dosen_pengusul' => 'reny rustyawati',
                    'phone_dosen'         => '85241890087',
                    'fakultas'            => 'fpsi',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'andes sugianto, s. pd.',
                    'jabatan'             => 'guru smk',
                    'instansi'            => 'smks islam jipang, bantarkawung',
                    'email'               => 'andessugianto2728@gmail.com',
                    'phone_responden'     => '85228773173',
                    'nama_dosen_pengusul' => 'erfi firmansyah',
                    'phone_dosen'         => '85691554888',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr.',
                    'fullname'            => 'rahmat, s.ag., m.hum.',
                    'jabatan'             => 'kepala kantor bahasa',
                    'instansi'            => 'kantor bahasa kepri',
                    'email'               => 'rahmatzainunabd@gmail.com',
                    'phone_responden'     => '85370337451',
                    'nama_dosen_pengusul' => 'erfi firmansyah',
                    'phone_dosen'         => '85691554888',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'ms',
                    'fullname'            => 'neni nurkhamidah, m.pd',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas media nusantara citra',
                    'email'               => 'neninurkhamidah@gmail.com',
                    'phone_responden'     => '85943156762',
                    'nama_dosen_pengusul' => 'erfi firmansyah',
                    'phone_dosen'         => '85691554888',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'lidia simanjuntak',
                    'jabatan'             => 'staf humas',
                    'instansi'            => 'bank indonesia kpw dki jakarta',
                    'email'               => 'lidia_s@bigo. id',
                    'phone_responden'     => '85275184539',
                    'nama_dosen_pengusul' => 'destria kurnianti',
                    'phone_dosen'         => '87729871221',
                    'fakultas'            => 'fe',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs.',
                    'fullname'            => 'ratna indah nurviyanti',
                    'jabatan'             => 'direktur umum',
                    'instansi'            => 'pt. relindo utama',
                    'email'               => 'ratnaindah_fe@yahoo.co.id',
                    'phone_responden'     => '81212827970',
                    'nama_dosen_pengusul' => 'destria kurnianti',
                    'phone_dosen'         => '87739871221',
                    'fakultas'            => 'fe',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'd',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'prince of songkla university, hat yai, thailand',
                    'email'               => 'juang.r@psu.ac.th',
                    'phone_responden'     => '66631137563',
                    'nama_dosen_pengusul' => 'dr. li. rizdika mardiana, m.pd.',
                    'phone_dosen'         => '8161965528',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'ahmad kamil ghazali',
                    'jabatan'             => 'coordinator of french program',
                    'instansi'            => 'universiti malaya',
                    'email'               => 'akamil@um.edu.my',
                    'phone_responden'     => '60126535550',
                    'nama_dosen_pengusul' => 'ratna, s. pd, m. hum',
                    'phone_dosen'         => '81381727208',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'frina diniarta nur, m. hum',
                    'jabatan'             => 'dosen bahasa inggris',
                    'instansi'            => 'institut bisnis nusantara',
                    'email'               => 'frinadiniarta@gmail.com',
                    'phone_responden'     => '816-1164-010',
                    'nama_dosen_pengusul' => 'ratna, s. pd, m. hum',
                    'phone_dosen'         => '81381727208',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'dr. farida amalia, m. pd',
                    'jabatan'             => 'dosen bahasa prancis',
                    'instansi'            => 'universitas pendidikan indonesia',
                    'email'               => 'faridaamalia@upi.edu',
                    'phone_responden'     => '821-2666-3326',
                    'nama_dosen_pengusul' => 'ratna, s. pd, m. hum',
                    'phone_dosen'         => '81381727208',
                    'fakultas'            => 'fbs',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'dr.li. nunung nurhayati, m.pd',
                    'jabatan'             => 'kaprodi pendidikan bahasa inggris',
                    'instansi'            => 'universitas setia budhi rangkasbitung',
                    'email'               => 'nunung.nurhayati@usbr.ac.id',
                    'phone_responden'     => '81281584348',
                    'nama_dosen_pengusul' => 'dr.li. rizdika mardiana, m.pd.',
                    'phone_dosen'         => '0816-1965-528',
                    'fakultas'            => 'fkip',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'novia cyntia dewi',
                    'jabatan'             => 'pengajar',
                    'instansi'            => 'teras mandarin',
                    'email'               => 'noviachyntiad@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'cintasya nisalifia',
                    'jabatan'             => 'owner',
                    'instansi'            => 'cintasyanart',
                    'email'               => 'cnisalifia@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'yolanda iswardani',
                    'jabatan'             => 'owner',
                    'instansi'            => 'yooiswrdn',
                    'email'               => 'yolanda.iswardani1796@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'yoshi paulina',
                    'jabatan'             => 'manager',
                    'instansi'            => 'pauline language center',
                    'email'               => 'yoshi.paulina@yahoo.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'dewi suharyanti',
                    'jabatan'             => 'owner',
                    'instansi'            => 'aiming mandarin',
                    'email'               => 'dewisuharyanti97@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'frans winata',
                    'jabatan'             => 'owner',
                    'instansi'            => 'frans mandarin',
                    'email'               => 'pacinzone@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'haikal hafiz',
                    'jabatan'             => 'ceo',
                    'instansi'            => 'cici pethouse',
                    'email'               => 'dinastyical@yahoo.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'sagitah rizkyah lestari',
                    'jabatan'             => 'staf',
                    'instansi'            => 'seameo qitep in language',
                    'email'               => 'sagitarizkyah22@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'rere agita putri',
                    'jabatan'             => 'cro',
                    'instansi'            => 'pt. kisi',
                    'email'               => 'rerewap@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'novitasari',
                    'jabatan'             => 'costumer assistant',
                    'instansi'            => 'pt bank icbc indonesia',
                    'email'               => 'opinovita23@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'delsy aulia',
                    'jabatan'             => 'purchasing officer',
                    'instansi'            => 'pt. indonesia weda bay industrial park',
                    'email'               => 'dlsyauliaa@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'rullin aulia fatma',
                    'jabatan'             => 'supervisor',
                    'instansi'            => 'fastock warehouse service indonesia',
                    'email'               => 'rullinatmaf@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'pramawati andaru',
                    'jabatan'             => 'pengajar',
                    'instansi'            => 'xinle learning center',
                    'email'               => 'pramawatiandaru@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'kelly novera',
                    'jabatan'             => 'pengajar',
                    'instansi'            => 'motessori gading permata school',
                    'email'               => 'kellynovella52@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'kristi julian',
                    'jabatan'             => 'purchasing mandarin speaker',
                    'instansi'            => 'pt wook global technology',
                    'email'               => 'kristijuliaan@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'liener',
                    'jabatan'             => 'translator coordinator',
                    'instansi'            => 'anton oil services indo',
                    'email'               => 'lienerfadli@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'm gilang fajrianto',
                    'jabatan'             => 'pengajar',
                    'instansi'            => 'suberta',
                    'email'               => 'gilangfajrianto@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'jefry alexander',
                    'jabatan'             => 'marketing officer',
                    'instansi'            => 'pt. jupiter indonesia & cv. tri angels',
                    'email'               => 'liuwenhao16@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'angelica maria',
                    'jabatan'             => 'contract specialist executive',
                    'instansi'            => 'pt. indonesia morowali industrial park',
                    'email'               => 'angelicamw05@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mrs',
                    'fullname'            => 'annisa fitrah ramadhan',
                    'jabatan'             => 'pengajar',
                    'instansi'            => 'pt. taiwan new south center indonesia',
                    'email'               => 'annisafitrah33@gmail.com',
                    'phone_responden'     => '',
                    'nama_dosen_pengusul' => 'aprilia ruby wikarti',
                    'phone_dosen'         => '8979608797',
                    'fakultas'            => 'fbs',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'ahmad sahidah',
                    'jabatan'             => 'dosen filsafat keuangan',
                    'instansi'            => 'universitas nurul jadid',
                    'email'               => 'ahmadsahidah@unuja.ac.id',
                    'phone_responden'     => '6285294511228',
                    'nama_dosen_pengusul' => '',
                    'phone_dosen'         => '',
                    'fakultas'            => '',
                    'category'            => '',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'hermawan risky eko priambodo',
                    'jabatan'             => 'analisis barang milik negara kkp',
                    'instansi'            => 'kementerian kelautan dan perikanan',
                    'email'               => 'hermawanrisky99@gmail.com',
                    'phone_responden'     => '081347501279',
                    'nama_dosen_pengusul' => 'murien nugraheni',
                    'phone_dosen'         => '085643687541',
                    'fakultas'            => 'ft',
                    'category'            => 'employer',
                ],
                [
                    'title'               => 'ms',
                    'fullname'            => 'fryda fatmayati',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'sekolah tinggi teknologi kedirgantaraan (sttkd)',
                    'email'               => 'fryda.fatmayati@sttkd.ac.id',
                    'phone_responden'     => '082392176135',
                    'nama_dosen_pengusul' => 'murien nugraheni',
                    'phone_dosen'         => '085643687541',
                    'fakultas'            => 'ft',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'ms',
                    'fullname'            => 'ika arfiani',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas ahmad dahlan',
                    'email'               => 'ika.arfiani@tif.uad.ac.id',
                    'phone_responden'     => '085646976454',
                    'nama_dosen_pengusul' => 'murien nugraheni',
                    'phone_dosen'         => '085643687541',
                    'fakultas'            => 'ft',
                    'category'            => 'academic',
                ],
                [
                    'title'               => 'mr',
                    'fullname'            => 'agung maulana',
                    'jabatan'             => 'dosen',
                    'instansi'            => 'universitas nusa putra',
                    'email'               => 'agung.maulana@nusaputra.ac.id',
                    'phone_responden'     => '85892849749',
                    'nama_dosen_pengusul' => 'putri haryani',
                    'phone_dosen'         => '81373886446',
                    'fakultas'            => 'feb',
                    'category'            => 'academic',
                ],
            ]

        );
    }
}
