<?php

return [
    // INDIKATOR 1
    1 => [
        1 => [
            0 => 'Tidak ditemui ide baru yang memberi solusi.',
            1 => 'Ide baru bersifat Inkremental, belum menawarkan solusi.',
            2 => 'Ide bersifat Inkremental dan menawarkan solusi.',
            3 => 'Ide bersifat Distinctive dan belum menawarkan solusi.',
            4 => 'Ide bersifat Distinctive dan sudah menawarkan solusi yang tepat.',
            5 => 'Ide bersifat terobosan dan mengubah, serta memberikan solusi yang tepat.',
        ],
        2 => [
            0 => 'Belum dilakukan pengamatan prinsip-prinsip ilmiah dasar dan publikasi ilmiah.',
            1 => 'Telah dilakukan pengamatan tetapi belum memiliki dukungan ilmiah yang kuat.',
            2 => 'Telah dilakukan pengamatan yang memberikan dukungan ilmiah namun lemah bagi keberhasilan mewujudkan ide.',
            3 => 'Telah dilakukan pengamatan yang memberikan dukungan ilmiah dan cukup kuat bagi keberhasilan mewujudkan ide.',
            4 => 'Telah dilakukan pengamatan sehingga memberikan dukungan ilmiah yang kuat bagi keberhasilan mewujudkan ide.',
            5 => 'Telah dilakukan pengamatan sehingga memberikan dukungan ilmiah yang sangat kuat bagi keberhasilan mewujudkan ide.',
        ],
        3 => [
            0 => 'Tidak memiliki unsur kebaruan dan daya beda dengan temuan lainnya.',
            1 => 'Memiliki daya beda dengan temuan lain tetapi tidak memiliki unsur kebaruan.',
            2 => 'Memiliki kebaruan tetapi daya beda dengan temuan lain lemah.',
            3 => 'Kebaruan bersifat inkremental (berkembang sedikit demi sedikit secara teratur) dan daya beda yang kuat.',
            4 => 'Kebaruan bersifat khas, dan daya beda yang kuat.',
            5 => 'Kebaruan bersifat lompatan dan daya beda yang kuat.',
        ],
        4 => [
            0 => 'Belum dapat diidentifikasi tahapan riset dan targetnya.',
            1 => 'Tahapan riset dan targetnya sudah mencapai tahap Perencanaan.',
            2 => 'Tahapan riset dan targetnya sudah mencapai tahap Perencanaan dan Pelaksanaan.',
            3 => 'Tahapan riset dan targetnya sudah mencapai tahap Perencanaan, Pelaksanaan dan Pelaporan Penelitian.',
            4 => 'Tahapan riset dan targetnya: Sudah Memiliki Purnarupa (Prototype).',
            5 => 'Purnarupa (protype) sudah terbukti kebenaran dan keamanannya.',
        ],
        5 => [
            0 => 'Belum dilakukan Pengujian.',
            1 => 'Dalam persiapan Pengujian.',
            2 => 'Telah dilakukan Pengujian Awal Teori.',
            3 => 'Telah dilakukan Pengujian Awal Teori, secara Intensif, namun belum dapat disimpulkan.',
            4 => 'Telah dilakukan Pengujian Awal Teori, secara Intensif, hampir diperoleh kesimpulan.',
            5 => 'Telah dilakukan Pengujian Awal Teori, secara Intensif, sudah diperoleh kesimpulan.',
        ],
        6 => [
            0 => 'Produk Inovasi belum memperhatikan kebutuhan pasar.',
            1 => 'Produk Inovasi sedikit memperhatikan kebutuhan pasar.',
            2 => 'Produk Inovasi sudah berorientasi kebutuhan pasar.',
            3 => 'Produk Inovasi sudah berorientasi kebutuhan pasar, namun belum ada riset pada pasar.',
            4 => 'Produk Inovasi sudah berorientasi kebutuhan pasar, ada riset pasar, belum terjadi feedback dari pelanggan.',
            5 => 'Produk Inovasi sudah berorientasi kebutuhan pasar, ada riset pasar, belum terjadi feedback dari pelanggan.',
        ],
        7 => [
            0 => 'Tidak dilakukan riset pasar.',
            1 => 'Telah dilakukan riset pasar, tetapi belum teridentifikasi: keinginan, kebutuhan, permintaan pelanggan.',
            2 => 'Telah dilakukan riset pasar, dan teridentifikasi: kebutuhan pelanggan.',
            3 => 'Telah dilakukan riset pasar, dan teridentifikasi: keinginan pelanggan.',
            4 => 'Telah dilakukan riset pasar, dan teridentifikasi: permintaan pelanggan.',
            5 => 'Telah dilakukan riset pasar, sudah teridentifikasi: keinginan, kebutuhan dan permintaan pelanggan.',
        ],
        8 => [
            0 => 'Belum dilakukan riset pasar.',
            1 => 'Persiapan dan mulai dilakukan riset pasar.',
            2 => 'Telah dilakukan riset pasar dan teridentifikasi: Variabel Geografis.',
            3 => 'Telah dilakukan riset pasar dan teridentifikasi: Opsi lokasi pasar yang akan dituju.',
            4 => 'Sedang dilakukan pengujian riset pasar pada opsi pasar yang dituju.',
            5 => 'Sudah dilakukan riset pasar dan memilih lokasi pasar yang akan dituju.',
        ],
        9 => [
            0 => 'Belum memiliki strategi inovasi.',
            1 => 'Tahap persiapan penyusunan strategi inovasi.',
            2 => 'Dalam penyusunan strategi inovasi.',
            3 => 'Telah menyusun strategi, namun belum diterapkan.',
            4 => 'Telah menyusun strategi, dan telah menetapkan strategi inovasi.',
            5 => 'Telah menyusun strategi, dan telah menetapkan dan menjalankan strategi inovasi.',
        ],
        10 => [
            0 => 'Belum didefiniskan lingkup proyek dan tugas tim.',
            1 => 'Tahap persiapan penyusunan lingkup proyek dan tugas tim.',
            2 => 'Tahap penyusunan lingkup proyek dan tugas tim.',
            3 => 'Penyusunan lingkup proyek dan tugas tim sudah selesai.',
            4 => 'Penyusunan lingkup proyek dan tugas tim sudah selesai dan masih dalam proses penetapan.',
            5 => 'Penyusunan lingkup proyek dan tugas tim sudah selesai dan sudah ditetapkan.',
        ],
        11 => [
            0 => 'Belum ada kepastian sumber daya (SDM & SDA) dan dana serta fasilitas penelitian yang dibutuhkan.',
            1 => 'Hanya memiliki salah satu kepastian diantara: SDM, Laboratorium, Sumber Dana.',
            2 => 'Sudah memiliki dua kepastian diantara: SDM, Laboratorium, Sumber Dana.',
            3 => 'Sudah memiliki kepastian SDM, Laboratorium, Sumber Dana.',
            4 => 'Sudah memiliki kepastian SDM, Laboratorium, Sumber Dana, tetapi masih membutuhkan dukungan layanan lainnya.',
            5 => 'Sudah memiliki kepastian SDM, Laboratorium, Sumber Dana dan dukungan layanan lainnya.',
        ],
        12 => [
            0 => 'Tidak ada akses komunikasi Digital.',
            1 => 'Hanya ada saluran Telepon.',
            2 => 'Hanya ada saluran telepon dan perpustakaan.',
            3 => 'Ada saluran Telepon dan salah satu diantara: Jaringan Internet atau Perpustakaan.',
            4 => 'Ada saluran Telepon dan Perpustakaan serta jaringan internet.',
            5 => 'Ada saluran Telepon, Jaringan Internet, Perpustakaan dan E-Library.',
        ],
        13 => [
            0 => 'Belum teridentifikasi implikasi dasar manufaktur.',
            1 => 'Persiapan pelaksanaan identifikasi awal implikasi dasar manufaktur.',
            2 => 'Telah dilakukan identifikasi awal implikasi dasar manufaktur.',
            3 => 'Telah teridentifikasi implikasi dasar manufaktur secara teknis.',
            4 => 'Telah teridentifikasi implikasi dasar manufaktur secara teknis dan dalam proses identifikasi dasar manufaktur secara ekonomis.',
            5 => 'Teridentifikasi implikasi (konsekuensi atau akibat langsung dari hasil penemuan suatu penelitian ilmiah) dasar manufaktur.',
        ],
        14 => [
            0 => 'Belum teridentifikasi konsep manufaktur.',
            1 => 'Persiapan pelaksanaan identifikasi konsep manufaktur.',
            2 => 'Telah dilakukan identifikasi awal konsep manufaktur.',
            3 => 'Telah teridentifikasi konsep manufaktur dalam pengertian proses manufaktur secara teknis.',
            4 => 'Proses penyelesaian konsep manufaktur dalam pengertian proses manufaktur secara ekonomis.',
            5 => 'Telah teridentifikasi konsep manufaktur: Proses manufaktur secara teknis dan ekonomis.',
        ],
        15 => [
            0 => 'Belum dilakukan validasi konsep manufaktur melalui analitik atau eksperimen laboratorium.',
            1 => 'Tahap persiapan validasi konsep manufaktur melalui analitik atau eksperimen laboratorium.',
            2 => 'Telah dilakukan validasi awal konsep manufaktur melalui analitik atau eksperimen laboratorium, dengan capaian 40%.',
            3 => 'Telah dilakukan validasi konsep manufaktur melalui analitik atau eksperimen laboratorium dengan capaian 60%.',
            4 => 'Telah dilakukan validasi konsep manufaktur melalui analitik atau eksperimen laboratorium dengan capaian 80%.',
            5 => 'Telah diselesaikan validasi konsep manufaktur melalui analitik atau eksperimen laboratorium, dan telah diperoleh bukti konsep manufaktur.',
        ],
        16 => [
            0 => 'Tidak punya konsep model bisnis untuk ide yang dikembangkan.',
            1 => 'Persiapan dan mulai menyusun konsep model bisnis berdasarkan ide yang dikembangkan.',
            2 => 'Sedang menyusun konsep model bisnis untuk ide yang dikembangkan.',
            3 => 'Konsep model bisnis untuk ide yang dikembangkan belum lengkap dan jelas.',
            4 => 'Konsep model bisnis untuk ide yang dikembangkan cukup lengkap dan jelas.',
            5 => 'Konsep model bisnis untuk ide yang dikembangkan lengkap dan jelas.',
        ],
        17 => [
            0 => 'Tidak ada analisis pelanggan, pasar dan pesaing dari ide yang dikembangkan.',
            1 => 'Sedang mulai menyusun analisis pelanggan, pasar dan pesaing terhadap ide yang dikembangkan.',
            2 => 'Hanya ada hasil analisis pesaing dari ide yang dikembangkan.',
            3 => 'Hanya Ada hasil analisis pelanggan dari ide yang dikembangkan.',
            4 => 'Hanya Ada hasil analisis pelanggan dan pesaing dari ide yang dikembangkan.',
            5 => 'Ada hasil analisis pelanggan, pasar dan pesaing dari ide yang dikembangkan.',
        ],
        18 => [
            0 => 'Tidak ada bukti bahwa ide yang dikembangkan telah memberikan solusi bagi pelanggan.',
            1 => 'Mulai dilakukan percobaan dan percontohan terhadap ide yang dikembangkan dapat memberi solusi bagi pelanggan.',
            2 => 'Percobaan dan percontohan telah selesai (belum dianalisis berdasarkan kekuatan, kelemahan, peluang dan tantangan- SWOT analysis).',
            3 => 'Ada bukti yang Lemah bahwa ide yang dikembangkan telah memberikan solusi bagi pelanggan.',
            4 => 'Ada bukti yang cukup kuat bahwa ide yang dikembangkan telah memberikan solusi bagi pelanggan.',
            5 => 'Ada bukti yang sangat kuat bahwa ide yang dikembangkan telah memberikan solusi bagi pelanggan.',
        ],
        19 => [
            0 => 'Belum ada strategi membangun jejaring kerja dan kemitraan.',
            1 => 'Tahap persiapan penyusunan strategi membangun jejaring kerja dan kemitraan.',
            2 => 'Identifikasi kekuatan, kelemahan, peluang dan ancaman dalam membangun jejaring kerja dan kemitraan.',
            3 => 'Analisis SWOT.',
            4 => 'Analisis faktor internal dan eksternal untuk menurunkan strategi.',
            5 => 'Telah diperoleh strategi membangun jejaring kerja dan kemitraan.',
        ],
        20 => [
            0 => 'Belum diidentifikasi mitra potensial.',
            1 => 'SeTahap persiapan identifikasi mitra potensial.',
            2 => 'Identifikasi awal terkait relevansi mitra dengan program pengembangan yang dilakukan.',
            3 => 'Identifikasi lanjutan, mencakup: relevansi mitra dengan program pengembangan yang dilakukan, serta peta peran dan kontribusi mitra.',
            4 => 'Tahap penyelesaian identifikasi, mencakup: relevansi mitra dengan program pengembangan yang dilakukan, peta peran dan kontribusi mitra, serta upaya memaksimalkan peran dan kontribusi mitra.',
            5 => 'Telah tersedia hasil identifikasi mitra potensial, mencakup: relevansi mitra dengan program pengembangan yang dilakukan, peta peran dan kontribusi mitra, serta upaya memaksimalkan peran dan kontribusi mitra.',
        ],
        21 => [
            0 => 'Tidak ada kajian risiko teknologi dan tidak menjadi pertimbangan dalam setiap langkah penelitian.',
            1 => 'Sedang disusun materi penelitian atau kajian risiko teknologi.',
            2 => 'Kajian risiko teknologi telah selesai (belum menjadi pertimbangan).',
            3 => 'Kajian risiko telah menjadi pertimbangan dalam beberapa langkah penelitian.',
            4 => 'Kajian risiko telah menjadi pertimbangan dalam hampir setiap langkah penelitian.',
            5 => 'Kajian risiko telah menjadi pertimbangan dalam setiap langkah penelitian.',
        ],
        22 => [
            0 => 'Tidak disusun rencana pengendalian risiko teknologi pada tahap penelitian.',
            1 => 'Memiki ide/gagasan pengendalian risiko teknologi pada tahap penelitian.',
            2 => 'Garis besar materi rencana pengendalian risiko teknologi pada tahap penelitian telah disusun.',
            3 => 'Mulai menyusun rencana pengendalian risiko teknologi pada tahap penelitian.',
            4 => 'Tahap penyelesaian penyusunan rencana pengendalian risiko teknologi pada tahap penelitian.',
            5 => 'Tersusun rencana pengendalian risiko teknologi pada tahap penelitian.',
        ],
    ],

    // INDIKATOR 2
    2 => [
        1 => [
            0 => 'Belum dilakukan validasi terhadap komponen individu dari teknologi.',
            1 => 'Persiapan pelaksanaan validasi dan uji komponen individu dari teknologi secara terpisah.',
            2 => 'Mulai dilakukan validasi dan uji komponen individu dari teknologi secara terpisah di lingkungan laboratorium.',
            3 => 'Telah selesai dan lolos validasi dan uji komponen individu dari teknologi secara terpisah di lingkungan laboratorium.',
            4 => 'Mulai dilakukan validasi dan uji di lingkungan simulasi.',
            5 => 'Telah selesai dan lolos validasi dan uji di lingkungan laboratorium dan simulasi.',
        ],
        2 => [
            0 => 'Belum dilakukan demonstrasi purnarupa (Prototype) a (alpha) pada lingkungan yang relevan.',
            1 => 'Persiapan untuk melaksanakan tahapan pembuatan purnarupa (Prototype) a (alpha).',
            2 => 'Telah dilakukan pembuatan purnarupa (Prototype) a (alpha) dan diketahui kondisi lingkungan operasi sesungguhnya.',
            3 => 'Telah diperoleh purnarupa (Prototype) a (alpha), diketahui kondisi lingkungan operasi, serta keberhasilan modeling & simulasi untuk kinerja sistem.',
            4 => 'Telah dilakukan pengujian Prototype) a (alpha) pada kondisi lingkungan operasi sesungguhnya.',
            5 => 'Telah dilakukan pengujian Prototype) a (alpha) dengan diketahui: kondisi lingkungan, kebutuhan investasi, proses fabrikasi, keberhasilan modeling & simulasi, serta hasil uji layak secara teknis (engineering feasibility).',
        ],
        3 => [
            0 => 'Teknologi belum layak secara teknis.',
            1 => 'Tahap persiapan pembuatan purnarupa (Prototype) a (alpha) untuk pengujian teknis.',
            2 => 'Purnarupa (prototype) a (alpha) diperoleh.',
            3 => 'Purnarupa (Prototype) a (alpha) telah diperoleh dan pengujian awal dilakukan',
            4 => 'Purnarupa (Prototype) a (alpha) telah diperoleh dan dilakukan iterasi pengujian.',
            5 => 'Teknologi dinyatakan layak secara teknis (engineering feasibility) melalui serangkaian pengujian.',
        ],
        4 => [
            0 => 'Belum dilakukan pendaftaran kekayaan intelektual.',
            1 => 'Tahap mempelajari persyaratan pendaftaran kekayaan intelektual.',
            2 => 'Tahap mempersiapkan persyaratan pendaftaran kekayaan intelektual.',
            3 => 'Tahap melengkapi persyaratan pendaftaran kekayaan intelektual',
            4 => 'Tahap pendaftaran kekayaan intelektual',
            5 => 'Telah terdaftar dan telah menerima bukti pembayaran biaya permohonan.',
        ],
        5 => [
            0 => 'Secara teknis belum memberikan solusi terhadap permasalahan yang dihadapi masyarakat.',
            1 => 'Tahap identifikasi kebutuhan solusi terhadap permasalahan yang dihadapi masyarakat.',
            2 => 'Sistem yang diajukan cukup praktis karena teknologi yang tersedia cukup untuk diaplikasikan.',
            3 => 'Hanya syarat 1 dan 2 yang telah terpenuhi.',
            4 => 'Hanya syarat 1, 2, dan 3 yang telah terpenuhi.',
            5 => 'Keempat Syarat Kelayakan Teknis telah terpenuhi.',
        ],
        6 => [
            0 => 'Tidak ada identifikasi terhadap pelanggan akhir yang ingin disasar.',
            1 => 'Telah dimulai proses identifikasi pelanggan akhir.',
            2 => 'Proses awal identifikasi pelangan akhir telah dilakukan.',
            3 => 'Proses identifikasi pelanggan akhir telah selesai.',
            4 => 'Profil pelanggan akhir telah dianalisis.',
            5 => 'Rincian profil calon pelanggan akhir diuraikan secara lengkap.',
        ],
        7 => [
            0 => 'Tidak memiliki rencana peluncuran produk ke pasar (business plan).',
            1 => 'Memiliki ide/gagasan tentang rencana peluncuran produk ke pasar.',
            2 => 'Garis besar materi rencana strategi peluncuran produk ke pasar telah disusun.',
            3 => 'Dokumen strategi peluncuran produk ke pasar sedang disusun.',
            4 => 'Tahap analisi dan finalisasi penyusunan dokumen strategi peluncuran produk ke pasar.',
            5 => 'Dokumen strategi peluncuran produk (business plan) yang lengkap mencakup STP dan 4P telah selesai.',
        ],
        8 => [
            0 => 'Tidak ada informasi terkait modal intelektual.',
            1 => 'Ada ide/gagagsan untuk menyiapkan modal intelektual.',
            2 => 'Mulai disiapkan penyusunan rincian modal intelektual.',
            3 => 'Tahap finalisasi penyusunan rincian modal intelektual',
            4 => 'Rincian modal intelektual telah disiapkan dan diuraikan tidak secara lengkap.',
            5 => 'Rincian modal intelektual telah disiapkan dan diuraikan secara lengkap.',
        ],
        9 => [
            0 => 'Belum disusun analisis dan rencana bisnis.',
            1 => 'Persiapan penyusunan rencana bisnis.',
            2 => 'Mulai penyusunan awal rencana bisnis.',
            3 => 'Tahap penyelesaian analisis bisnis.',
            4 => 'Telah diselesaikan analisis bisnis, dan tahap penyelesaian rencana bisnis',
            5 => 'Telah dikeluarkan analisis dan rencana bisnis.',
        ],
        10 => [
            0 => 'Tidak memiliki dan melibatkan individu-individu kunci.',
            1 => 'Memiliki beberapa individu kunci yang memiliki keahlian unik, tetapi tidak dilibatkan secara aktif.',
            2 => 'Memiliki beberapa individu kunci dengan keahlian uniknya, tetapi kurang diberikan tanggung jawab pada posisi strategis.',
            3 => 'Memiliki beberapa individu kunci dengan keahlian uniknya dan diberikan tanggung jawab pada posisi yang strategis.',
            4 => 'Memiliki individu-individu kunci dengan keahlian uniknya yang sulit digantikan (berkaitan dengan jumlah), tetapi belum secara optimal diberikan tanggung jawab pada posisi yang strategis.',
            5 => 'Memiliki individu-individu kunci dengani keahlian uniknya yang sulit digantikan (berkaitan dengan jumlah) dan diberikan tanggung jawab pada posisi yang strategis.',
        ],
        11 => [
            0 => 'Belum ada persyaratan proyek dan daftar mitra proyek.',
            1 => 'Dalam proses identifikasi persyaratan proyek dan daftar mitra proyek.',
            2 => 'Sudah ada persyaratan proyek, tetapi belum ada mitra, atau sebaliknya.',
            3 => 'Sudah ada persyaratan proyek dan daftar mitra proyek, tetapi belum disetujui.',
            4 => 'Sudah ada persyaratan proyek dan daftar mitra proyek, dan dalam proses persetujuan.',
            5 => 'Sudah ada persyaratan proyek dan daftar mitra proyek yang telah disetujui.',
        ],
        12 => [
            0 => 'Belum ada tanggung jawab dan persetujuan batas waktu proyek.',
            1 => 'Dalam proses identifikasi beban dan tanggung jawab dalam pelaksanaan proyek, dan proses penyusunan jadwal.',
            2 => 'Sudah ada tanggungjawab proyek, tetapi belum ada batas waktu proyek, atau sebaliknya.',
            3 => 'Sudah ada tanggung jawab dan persetujuan batas waktu proyek, tetapi belum disetujui.',
            4 => 'Sudah ada penanggungjawab dan batas waktu proyek, dan dalam proses persetujuan.',
            5 => 'Telah tersedia penanggungjawab dan batas waktu proyek yang disetujui.',
        ],
        13 => [
            0 => 'Belum diidentifikasi teknologi dan komponen kritikal.',
            1 => 'Persiapan identifikasi teknologi dan komponen kritikal.',
            2 => 'Mulai dilakukan identifikasi awal teknologi & komponen kritikal dengan capaian 40%.',
            3 => 'Identifikasi teknologi dan komponen kritikal dalam penyelesaian dengan capaian 60%.',
            4 => 'Identifikasi teknologi dan komponen kritikal dalam penyelesaian dengan capaian 80%.',
            5 => 'Telah secara komplit (capaian 100%) diidentifikasi teknologi dan komponen kritikal.',
        ],
        14 => [
            0 => 'Belum dapat diperlihatkan kesiapan sub system/system dalam suatu lingkungan produksi yang relevan.',
            1 => 'Tahap persiapan awal membangun kesiapan sub system/system dalam suatu lingkungan produksi yang relevan',
            2 => 'Telah diperlihatkan kesiapan sub system/system dalam suatu lingkungan produksi yang relevan yang mencakup kesiapan material.',
            3 => 'Telah diperlihatkan kesiapan sub system/system dalam suatu lingkungan produksi yang relevan yang mencakup kesiapan material dan perkakas',
            4 => 'Telah diperlihatkan kesiapan sub system/system dalam suatu lingkungan produksi yang relevan yang mencakup kesiapan material, perkakas dan alat uji prototype.',
            5 => 'Telah diperlihatkan kesiapan sub system/system dalam suatu lingkungan produksi yang relevan yang mencakup kesiapan material, perkakas, alat uji prototype, dan keahlian personel.',
        ],
        15 => [
            0 => 'Tidak ada bukti bahwa solusi yang ditawarkan kepada pelanggan memunculkan daya tarik yang menguntungkan di pasar.',
            1 => 'Memiliki keunggulan nilai jual namun belum melakukan survey pasar.',
            2 => 'Keunggulan nilai jual (value proposition) sedang di uji terap melalui survey pasar.',
            3 => 'Memiliki keunggulan nilai jual dibanding dengan kompetitor untuk pasar yang terbatas.',
            4 => 'Keunggulan nilai jual (value proposition) sedang diverifikasi dan divalidasi melalui uji terap untuk pasar yang lebih luas.',
            5 => 'Memiliki keunggulan dibanding kompetitor dan teruji dalam survey pasar yang lebih luas.',
        ],
        16 => [
            0 => 'Tidak ada bukti bahwa solusi yang ditawarkan kepada pelanggan memunculkan daya tarik yang menguntungkan di pasar.',
            1 => 'Ide yang dikembangkan menjadi prototype sesuai dengan kebutuhan pelanggan.',
            2 => 'Prototype yang dikembangkan memiliki nilai lebih dibanding kompetitor.',
            3 => 'Prototype yang dikembangkan dilakukan uji pasar',
            4 => 'Dilakukan proyeksi keuntungan terhadap prototype yang dikembangkan.',
            5 => 'Diperoleh proyeksi keuntungan dari prototype yang dikembangkan.',
        ],
        17 => [
            0 => 'Tidak ada bukti dilakukannya: validasi value proposition, channel, segmen pelanggan, model hubungan dengan pelanggan yang ada, dan aliran revenue.',
            1 => 'Telah ditetapkan MPV dan segmen pelanggan.',
            2 => 'Telah ditetapkan channel dan model hubungan dengan pelanggan yang ada.',
            3 => 'Telah dihasilkan analisis aliran revenue.',
            4 => 'Telah dilakukan validasi antara MPV, segmen pelanggan, channel, hubungan dengan pelanggan yang ada dan aliran revenue.',
            5 => 'Bukti-bukti yang ada saling berkaitan dalam menentukan aliran revenue.',
        ],
        18 => [
            0 => 'Belum dilakukan penggalian informasi dan seleksi mitra.',
            1 => 'Dilakukan penggalian informasi mitra.',
            2 => 'Diperoleh database mitra, dan penyusunan kriteria untuk seleksi mitra.',
            3 => 'Diperoleh database mitra dan kriteria untuk seleksi mitra.',
            4 => 'Diperoleh database mitra dan kriteria seleksi mitra, serta mulai dilakukan seleksi mitra.',
            5 => 'Telah dilakukan penggalian informasi dan seleksi mitra, dan telah diperoleh database mitra, kriteria seleksi mitra dan calon mitra potensial hasil seleksi.',
        ],
        19 => [
            0 => 'Belum terbangun pola kemitraan yang tepat.',
            1 => 'Mengkaji konsep pola kemitraan.',
            2 => 'Telah diperoleh konsep pola kemitraan yang lebih tepat.',
            3 => 'Validasi konsep pola kemitraan yang lebih tepat.',
            4 => 'Upaya pembangunan pola kemitraan berdasar konsep yang disusun.',
            5 => 'Telah dibangun pola kemitraan yang lebih tepat dalam pengembangan usaha untuk mencapai tujuan bisnis bersama.',
        ],
        20 => [
            0 => 'Tidak ada kajian risiko teknologi dan tidak menjadi pertimbangan dalam setiap tahap pengembangan teknologi.',
            1 => 'Sedang disusun materi penelitian atau kajian risiko teknologi dalam setiap tahap pengembangan teknologi.',
            2 => 'Kajian risiko teknologi pada setiap tahap pengembangan teknologi telah selesai (belum menjadi pertimbangan).',
            3 => 'Kajian risiko telah menjadi pertimbangan dalam beberapa tahap pengembangan teknologi.',
            4 => 'Kajian risiko telah menjadi pertimbangan dalam hampir setiap tahap pengembangan teknologi.',
            5 => 'Kajian risiko telah menjadi pertimbangan dalam setiap tahap pengembangan teknologi.',
        ],
        21 => [
            0 => 'Tidak disusun rencana pengendalian risiko teknologi pada tahap pengembangan teknologi.',
            1 => 'Memiki ide/gagasan pengendalian risiko teknologi pada tahap pengembangan teknologi.',
            2 => 'Garis besar materi rencana pengendalian risiko teknologi pada tahap tahap pengembangan teknologi telah disusun.',
            3 => 'Mulai menyusun rencana pengendalian risiko teknologi pada tahap pengembangan teknologi.',
            4 => 'Tahap penyelesaian penyusunan rencana pengendalian risiko teknologi pada tahap pengembangan teknologi.',
            5 => 'Tersusun rencana pengendalian risiko teknologi pada tahap tahap pengembangan teknologi.',
        ],
    ],

    // INDIKATOR 3
    3 => [
        1 => [
            0 => 'Belum diperoleh prototype',
            1 => 'Prototype dalam proses penyelesaian.',
            2 => 'Prototype sudah selesai.',
            3 => 'Prototype sedang dalam tahap pengujian dilingkungan sebenarnya.',
            4 => 'Prototype sudah selesai dalam pengujian dilingkungan sebenarnya.',
            5 => 'Telah berhasil dalam tahap pengujian prototype.',
        ],
        2 => [
            0 => 'Belum dilakukan uji eksternal',
            1 => 'Mempersiapkan uji eksternal',
            2 => 'Mulai dilakukan uji eksternal',
            3 => 'Uji eksternal berjalan 60%',
            4 => 'Uji eksternal berjalan 80%',
            5 => 'Telah diperoleh sertifikat hasil pengujian eksternal',
        ],
        3 => [
            0 => 'Tidak dilakukan dokumentasi',
            1 => 'Tahap : pencatatan kegiatan, dokumentasi petunjuk kerja, dan laporan teknis berkala',
            2 => 'Dalam proses menuju pengelolaan pencatatan kegiatan, dokumentasi petunjuk kerja, dan laporan teknis secara sistematis.',
            3 => 'Dalam pengelolaan pencatatan kegiatan, dokumentasi petunjuk kerja, dan laporan teknis secara sistematis. Tapi belum di dokumentasi.',
            4 => 'Dalam pengelolaan pencatatan kegiatan, dokumentasi petunjuk kerja, dan laporan teknis secara sistematis. Terdokumentasi namun belum teratur & terstruktur.',
            5 => 'Dokumentasi sudah teratur dan berstruktur.',
        ],
        4 => [
            0 => 'Belum memperkenalkan hasil inovasi.',
            1 => 'Perencanaan memperkenalkan hasil inovasi. Tetapi belum diputuskan: kapan, dimana, siapa, dan bagaimana.',
            2 => 'Perencanaan memperkenalkan hasil inovasi. Sudah diputuskan: kapan, dimana, siapa, dan bagaimana.',
            3 => 'Dalam persiapan memperkenalkan hasil inovasi.',
            4 => 'Telah dilakukan perkenalan hasil inovasi.',
            5 => 'Telah dilakukan perkenalan hasil inovasi, dan dapat diterima oleh pasar.',
        ],
        5 => [
            0 => 'Belum diperoleh kekayaan intelektual.',
            1 => 'Mempelajari persyaratan dalam memperoleh kekayaan intelektual.',
            2 => 'Persiapan persyaratan dalam memperoleh kekayaan intelektual.',
            3 => 'Telah mendapatkan surat submit dari Dirjen HKI.',
            4 => 'Menunggu keluarnya sertifikat kekayaan intelektual.',
            5 => 'Telah diperoleh sertifikat kekayaan intelektual.',
        ],
        6 => [
            0 => 'Belum dilakukan identifikasi dan analisis kebutuhan dan harapan pelanggan.',
            1 => 'Mengawali identifikasi: analisis kebutuhan dan harapan pelanggan.',
            2 => 'Penuangan hasil ide analisis kebutuhan dan harapan pelanggan kedalam tulisan.',
            3 => 'Sedang dilakukan identifikasi dan analisis kebutuhan dan harapan pelanggan.',
            4 => 'Identifikasi dan analisis kebutuhan dan harapan pelanggan telah selesai.',
            5 => 'Identifikasi dan analisis kebutuhan dan harapan pelanggan telah selesai dan tervalidasi.',
        ],
        7 => [
            0 => 'Belum diprediksi segmen.',
            1 => 'Persiapan survei dan kajian untuk prediksi segmen, ukuran serta pangsa pasar.',
            2 => 'Garis dasar serta garis besar materi riset data telah disusun.',
            3 => 'Garis dasar serta garis besar materi riset data dalam tahap pelaksanaan.',
            4 => 'Garis dasar serta garis besar materi riset data telah selesai dilaksanakan.',
            5 => 'Garis dasar serta garis besar materi riset data telah selesai dilaksanakan dan tervalidasi.',
        ],
        8 => [
            0 => 'Belum ada perkiraan harga.',
            1 => 'Sudah ada perkiraan harga, namun belum ada rencana perkenalan produk.',
            2 => 'Sudah ada perkiraan harga, sudah ada rencana perkenalan produk.',
            3 => 'Harga sudah diperkirakan, sudah ada rencana pengenalan, namun jenis produk belum rinci.',
            4 => 'Harga sudah diperkirakan menurut jenis produk, namun tidak lengkap.',
            5 => 'Harga sudah diperkirakan menurut jenis produk secara lengkap.',
        ],
        9 => [
            0 => 'Belum ada tuntutan penetapan organisasi.',
            1 => 'Sudah ada tuntutan bisnis namun belum diupayakan penetapan organisasi.',
            2 => 'Karena ada tuntutan bisnis maka mulai diupayakan penetapan organisasi.',
            3 => 'Upaya formalitas organisasi telah dilakukan, walaupun masih belum secara de jure dan de facto.',
            4 => 'Upaya formalitas organisasi telah dilakukan namun baru dilakukan salah satu cara diantara de facto atau de jure.',
            5 => 'Telah dilakukan formalitas organisasi secara de jure dan de facto untuk memenuhi tuntutan bisnis.',
        ],
        10 => [
            0 => 'Belum ada ide terkait dengan: identifikasi, evaluasi dan perencanaan SDM untuk menentukan kebutuhan tambahan staff.',
            1 => 'Kebutuhan tambahan staff dilakukan tanpa dilakukan identifikasi, evaluasi dan perencanaan SDM.',
            2 => 'Dalam menentukan kebutuhan tambahan staff mulai mempertimbangkan identifikasi, evaluasi dan perencanaan SDM.',
            3 => 'Kebutuhan tambahan staff telah dilakukan berdasar hasil identifikasi, evaluasi dan perencanaan SDM, walaupun belum terstruktur dan sistematis.',
            4 => 'Kebutuhan tambahan staff telah secara terstruktur dilakukan berdasar hasil identifikasi, evaluasi dan perencanaan SDM.',
            5 => 'Kebutuhan tambahan staff telah secara terstruktur dan sistematis melalui proses identifikasi, evaluasi dan perencanaan SDM.',
        ],
        11 => [
            0 => 'Tidak ada pembagian tanggung jawab dan beban kerja.',
            1 => 'Tahap identifikasi pembagian tanggung jawab dan beban kerja.',
            2 => 'Pembagian tanggung jawab dan beban kerja telah teridentifikasi.',
            3 => 'Mulai menerapkan pembagian tanggung jawab dan beban kerja.',
            4 => 'Telah dilaksanakan pembagian tanggung jawab dan beban kerja, walaupun belum secara terstruktur dan sistematis.',
            5 => 'Telah dilaksanakan pembagian tanggung jawab dan beban kerja secara terstruktur dan sistematis dengan menyesuaikan tuntutan bisnis.',
        ],
        12 => [
            0 => 'Desain sistem belum diperoleh.',
            1 => 'Proses pembentukan desain sistem.',
            2 => 'Telah diperoleh desain sistem.',
            3 => 'Desain sistem mulai dilakukan uji dan evaluasi.',
            4 => 'Pengulangan uji dan evaluasi desain sistem untuk memperoleh stabilitas desain sistem.',
            5 => 'Telah diperoleh desain sistem yang sebagian besar stabil melalui uji dan evaluasi.',
        ],
        13 => [
            0 => 'Masih pada tahap pengembangan proses dan prosedur manufaktur dalam skala laboratorium.',
            1 => 'Dalam proses uji dan validasi proses dan prosedur manufaktur dalam skala laboratorium.',
            2 => 'Tahap aktivitas pengembangan proses dan prosedur manufaktur dalam skala pilot.',
            3 => 'Telah diperoleh proses dan prosedur manufaktur dalam skala pilot, dan mulai dilakukan uji dan validasi proses dan prosedur manufaktur dalam skala pilot.',
            4 => 'Dalam proses pengulangan uji dan validasi proses dan prosedur manufaktur dalam skala pilot.',
            5 => 'Proses dan prosedur manufaktur telah terbukti dalam uji dan validasi skala pilot.',
        ],
        14 => [
            0 => 'Belum dibuat perancangan sistem atau metode produksi rinci.',
            1 => 'sedang dilakukan perancangan sistem atau metode produksi rinci melalui kegiatan pengembangan kerekayasaan dan manufaktur.',
            2 => 'Telah diperoleh perancangan sistem atau metode produksi rinci.',
            3 => 'Sedang dilakukan tahap uji terhadap hasil perancangan sistem atau metode produksi rinci.',
            4 => 'Tahap iterasi uji terhadap hasil perancangan sistem atau metode produksi rinci, dan telah menunjukkan stabil.',
            5 => 'Telah dilaksanakan Produksi awal laju rendah.',
        ],
        15 => [
            0 => 'Belum mendefinisikan kondisi akhir dari produk teknologi dengan mempertimbangkan target person, pasar vertikal, serta geografik',
            1 => 'Telah dilakukan analisis rantai bisnis.',
            2 => 'Telah diidentifikasi target person, pasar vertikal dan preferensi atau trend di wilayah geografik.',
            3 => 'telah dilakukan analisis pasar terhadap 2 dari 3 kategori pelanggan.',
            4 => 'Telah dilakukan analisis pasar terhadap semua kategori pelanggan.',
            5 => 'Produk yang dikembangkan sesuai dengan preferensi semua kategori pelanggan.',
        ],
        16 => [
            0 => 'Belum memvalidasi terhadap bisnis yang dilakukan.',
            1 => 'Telah ada konsep bisnis kanvas.',
            2 => 'Konsep model bisnis kanvas telah komprehensif.',
            3 => 'Telah diidentifikasi aspek aspek analisis kelayakan finansial.',
            4 => 'Telah dilakukan analisis kelayakan finansia',
            5 => 'Bisnis yang dikembangkan telah memenuhi analisis kelayakan finansial.',
        ],
        17 => [
            0 => 'Tidak ada bukti studi kelayakan penetapan Indikator kinerja utama terhadap kelayakan dan keberhasilan bisnis.',
            1 => 'Ada bukti yang lemah terhadap indikator kinerja utama dalam indikasi keberhasilan bisnis.',
            2 => 'Kelemahan bukti sedang disempurnakan.',
            3 => 'Penyempurnaan bukti telah selesai.',
            4 => 'Bukti penetapan IKU terhadap kelayakan dan keberhasilan bisnis telah dianalisis.',
            5 => 'Penetapan IKU terhadap kelayakan dan keberhasilan bisnis telah divalidasi .',
        ],
        18 => [
            0 => 'Dalam penjajakan menjalin kemitraan.',
            1 => 'Mulai terjalin kemitraan yang sifatnya belum formal dan mengikat.',
            2 => 'Tahap mencari pola kemitraan yang sifatnya formal dan mengikat.',
            3 => 'Disepakati untuk melakukan perjanjian yang sifatnya mengikat kedua pihak yang bermitra.',
            4 => 'Persiapan dokumen perjanjian yang sifatnya mengikat kedua pihak yang bermitra.',
            5 => 'Pola kemitraan telah disepakati dalam bentuk perjanjian, secara legal formal kemitraan tersebut telah memberikan ikatan bagi kedua pihak yang bermitra.',
        ],
        19 => [
            0 => 'Belum dibuat rencana kerjasama kemitraan.',
            1 => 'Tahap eksplorasi rencana kerjasama yang akan disusun.',
            2 => 'Mulai dilakukan penyusunan bersama rencana kerjasama.',
            3 => 'Penyelesaian dokumen rencana kerjasama.',
            4 => 'Telah diperoleh dokumen rencana kerjasama.',
            5 => 'Telah ada dokumen dan penerapan rencana kerjasama.',
        ],
        20 => [
            0 => 'Tidak disusun rencana pengendalian risiko pada tahap engineering dan operation.',
            1 => 'Mulai diinisiasi dan disiapkan rencana pengendalian risiko pada tahap engineering dan operation',
            2 => 'Telah disusun garis besar rencana pengendalian risiko pada tahap engineering dan operation.',
            3 => 'Sedang disusun rencana pengendalian risiko teknologi pada tahap engineering dan operation.',
            4 => 'Selesai disusun rencana pengendalian risiko teknologi pada tahap engineering dan operation.',
            5 => 'Rencana pengendalian risiko teknologi pada tahap engineering dan operation telah divalidasi.',
        ],
        21 => [
            0 => 'Tidak disusun rencana pengendalian risiko pada tahap penerapan teknologi.',
            1 => 'Mulai diinisiasi dan disiapkan rencana pengendalian risiko pada tahap penerapan teknologi.',
            2 => 'Telah disusun garis besar rencana pengendalian risiko pada tahap penerapan teknologi.',
            3 => 'Sedang disusun rencana pengendalian risiko teknologi pada tahap penerapan teknologi.',
            4 => 'Selesai disusun rencana pengendalian risiko teknologi pada tahap penerapan teknologi.',
            5 => 'Rencana pengendalian risiko teknologi pada tahap penerapan teknologi telah tervalidasi.',
        ],
    ],

    // INDIKATOR 4
    4 => [
        1 => [
            0 => 'Belum ada buku manual.',
            1 => 'Tersedia spesifikasi teknis saja.',
            2 => 'Tersedia spesifikasi teknis dan cara penggunaan.',
            3 => 'Tersedia spesifikasi teknis, cara penggunaan dan cara perawatan.',
            4 => 'Tersedia spesifikasi teknis, cara penggunaan, cara perawatan dan petunjuk teknis bila terjadi masalah.',
            5 => 'Tersedia spesifikasi teknis, cara penggunaan, cara perawatan, petunjuk teknis bila terjadi masalah dan dilengkapi alamat costomer service.',
        ],
        2 => [
            0 => 'Belum diidentifikasi penggunaan umumnya.',
            1 => 'Pada tahap uji dan validasi di lingkungan laboratorium.',
            2 => 'Pada tahap uji dan validasi di kondisi yang hampir menyerupai lingkungannya.',
            3 => 'Pada tahap uji dan validasi di kondisi yang lingkungan sebenarnya.',
            4 => 'Telah diperoleh sistem teknologi yang stabil.',
            5 => 'Telah ditetapkan penggunaan umum produk teknologi oleh pasar luas.',
        ],
        3 => [
            0 => 'Belum dilakukan pengujian untuk identifikasi keuntungan teknologi.',
            1 => 'Tahap persiapan pengujian untuk identifikasi keuntungan teknologi.',
            2 => 'Mulai dilakukan pengujian untuk identifikasi keuntungan teknologi.',
            3 => 'Telah dilakukan pengujian intensif, tetapi belum dapat diidentifikasi keuntungan teknologinya.',
            4 => 'Telah dilakukan pengujian intensif, mulai teridentifikasi keuntungan teknologinya.',
            5 => 'Telah dilakukan pengujian intensif, mulai teridentifikasi keuntungan teknologinya.',
        ],
        4 => [
            0 => 'Belum ada dukungan terhadap adopsi produk teknologi oleh pasar.',
            1 => 'Tahap awal: Proses memberikan edukasi kepada pasar.',
            2 => 'Telah terbangun kesadaran pasar terhadap produk teknologi.',
            3 => 'Telah terbangun kesadaran dan minat pasar terhadap produk teknologi.',
            4 => 'Telah terbangun kesadaran, minat, dan mencoba produk teknologi.',
            5 => 'Telah terjadi adopsi produk teknologi oleh pasar.',
        ],
        5 => [
            0 => 'Belum membangun citra produk teknologi kepada pasar.',
            1 => 'Persiapan untuk membangun citra produk teknologi kepada pasar.',
            2 => 'Menyusun garis besar strategi dan analisis isi untuk membangun citra produk teknologi kepada pasar',
            3 => 'Tahap penyelesaian strategi dan analisis isi untuk membangun citra produk teknologi kepada pasar.',
            4 => 'Strategi dan analisis isi untuk membangun citra produk teknologi kepada pasar telah tersusun.',
            5 => 'Hasil analisis isi dan strategi untuk membangun citra produk teknologi kepada pasar telah diimplementasikan secara faktual.',
        ],
        6 => [
            0 => 'Model bisnis belum ditetapkan.',
            1 => 'Persiapan perancangan model bisnis.',
            2 => 'Garis besar konsep dan materi model bisnis telah disusun.',
            3 => 'Perancangan dan penyelesaian model bisnis.',
            4 => 'Hasil rancang model bisnis telah dianalisis.',
            5 => 'Model bisnis telah ditetapkan.',
        ],
        7 => [
            0 => 'Pesaing belum teridentifikasi.',
            1 => 'Persiapan kajian identifikasi pesaing.',
            2 => 'Garis besar konsep identifikasi pesaing telah disusu',
            3 => 'Kajian identifikasi pesaing telah dirancang dan diselesaikan.',
            4 => 'Hasil kajian identifikasi pesaing telah dianalisis.',
            5 => 'Pesaing telah teridentifikasi dan ditetapkan.',
        ],
        8 => [
            0 => 'Belum dilakukan tahap perkenalan produk kepada pelanggannya di pasar',
            1 => 'Persiapan strategi pengenalan (promosi) produk kepada pelanggannya di pasar.',
            2 => 'Mulai menyusun garis besar strategi dan materi pengenalan (promosi) produk kepada pelanggannya di pasar.',
            3 => 'Strategi dan materi pengenalan (promosi) telah di analisis.',
            4 => 'Strategi dan materi pengenalan (promosi) mulai dijalankan',
            5 => 'Promosi dan pemasaran berjalan dengan efektif sehingga perusahaan memperoleh nilai tambah.',
        ],
        9 => [
            0 => 'Belum ada organisasi.',
            1 => 'Telah ada organisasi R&D (Research & Development).',
            2 => 'Proses pengubahan organisasi R&D menjadi organisasi bisnis, walaupun belum ditetapkan bentuk organisasinya.',
            3 => 'Organisasi R&D telah menjadi organisasi bisnis, walaupun belum ditetapkan bentuk organisasinya.',
            4 => 'Organisasi R&D telah menjadi organisasi bisnis dan sudah ditetapkan bentuk organisasinya. Tapi belum berbadan hukum.',
            5 => 'Telah ada bentuk organisasi bisnis dan berbadan hukum.',
        ],
        10 => [
            0 => 'Belum dilakukan pengembangan kemitraan dengan organisasi independen.',
            1 => 'Tahap persiapan pengembangan kemitraan dengan organisasi independen.',
            2 => 'Mulai dikembangkan kemitraan dengan organisasi independen',
            3 => 'Telah berkembang kemitraan dengan organisasi independen, tetapi belum bersifat formal dan mengikat.',
            4 => 'Mulai dibangun kemitraan dengan organisasi independen yang bersifat formal dan mengikat.',
            5 => 'Telah terbangun kemitraan dengan organisasi independen yang bersifat formal dan mengikat.',
        ],
        11 => [
            0 => 'Belum ada produk baru yang diperkenalkan kepada mitra dan pasar baru.',
            1 => 'Tahap pengembangan produk baru.',
            2 => 'Tahap penyelesaian pengembangan produk baru.',
            3 => 'Telah diperoleh produk baru yang siap diperkenalkan ke pasar',
            4 => 'Proses identifikasi peluang untuk memperkenalkan produk kepada mitra dan pasar baru.',
            5 => 'Telah diidentifikasi peluang untuk memperkenalkan produk dan mulai dilakukan pengenalan.',
        ],
        12 => [
            0 => 'Telah diperoleh perancangan dan sistem metode produksi rinci, namun belum menunjukkan produksi yang menguntungkan secara finansial.',
            1 => 'Sedang dilakukan tahap uji terhadap hasil perancangan sistem atau metode produksi rinci yang menguntungkan secara finansial.',
            2 => 'Tahap uji yang berulang-ulang terhadap hasil perancangan sistem atau metode produksi rinci, dan telah menunjukkan kestabilan',
            3 => 'Sudah dilakukan produksi namun keuntungan finansial masih rendah.',
            4 => 'Persiapan produksi yang menguntungkan secara finansial dalam tahap uji dan evaluasi.',
            5 => 'Telah dilakukan produksi yang menguntungkan secara finansial.',
        ],
        13 => [
            0 => 'Produksi belum memenuhi ketentuan keamanan, kualitas, dan persyaratan hukum yang diberlakukan secara nasional maupun internasional.',
            1 => 'Tahap persiapan pengurusan ketentuan keamanan, kualitas, dan persyaratan hukum yang diberlakukan secara nasional maupun internasional',
            2 => 'Mulai dilakukan pengurusan secara administratif ketentuan keamanan, kualitas, dan persyaratan hukum yang diberlakukan secara nasional maupun internasional.',
            3 => 'Tahap verifikasi dan/atau appraisal oleh institusi berwenang dalam rangka memperoleh ketentuan keamanan, kualitas, dan persyaratan hukum yang diberlakukan secara nasional maupun internasional.',
            4 => 'Telah dinyatakan memenuhi ketentuan keamanan, kualitas, dan persyaratan hukum yang diberlakukan secara nasional maupun internasional.',
            5 => 'Produksi sudah melaksanakan dan memenuhi ketentuan keamanan, kualitas, dan persyaratan hukum yang diberlakukan secara nasional maupun internasional',
        ],
        14 => [
            0 => 'Belum menerapkan jaminan mutu.',
            1 => 'Tahap persiapan menerapkan jaminan mutu.',
            2 => 'Mulai menerapkan jaminan mutu.',
            3 => 'Tahap pengurusan mendapatkan akreditasi jaminan mutu.',
            4 => 'Tahap verifikasi dan/atau appraisal oleh institusi berwenang dalam rangka memperoleh akreditasi jaminan mutu sesuai standar tertentu.',
            5 => 'Telah mendapatkan sertifikat dan melaksanakan jaminan mutu sesuai standar tertentu yang dipersyaratkan.',
        ],
        15 => [
            0 => 'Belum ada kesadaran memperhatikan tuntutan masyarakat terhadap mutu, keamanan dan keselamatan produk yang dimanfaatkan.',
            1 => 'Tahap munculnya kesadaran awal untuk menerima dan memenuhi tuntutan masyarakat terhadap mutu, keamanan dan keselamatan produk yang dimanfaatkan.',
            2 => 'Tahap melakukan upaya memperoleh tanggapan atau feedback dari masyarakat atau pelanggannya terhadap mutu, keamanan dan keselamatan produk yang dimanfaatkan.',
            3 => 'Telah menerima tanggapan atau feedback dari masyarakat atau pelanggannya terhadap mutu, keamanan dan keselamatan produk,, tetapi belum melakukan upaya untuk memenuhi tuntutan tersebut.',
            4 => 'Telah menerima dan memenuhi tuntutan dari terhadap mutu, keamanan dan keselamatan produk.',
            5 => 'Telah menerima dan memenuhi tuntutan secara optimal dari masyarakat atau pelanggannya terhadap mutu, keamanan dan keselamatan produk yang dimanfaatkan.',
        ],
        16 => [
            0 => 'Belum dilakukan identifikasi potensi pasar',
            1 => 'Mulai dilakukan identifikasi potensi pasar.',
            2 => 'Potensi pasar telah teridentifikasi.',
            3 => 'Hasil teridentifikasi potensi pasar mulai dianalisis.',
            4 => 'Hasil identifikasi potensi pasar telah selesai dianalisis.',
            5 => 'Telah diperkirakan daya serap konsumen terhadap produk/jasa yang ditawarkan melalui identifikasi dan analisis potensi pasar.',
        ],
        17 => [
            0 => 'Belum dilakukan identifikasi keberterimaan produk/jasa di pasar.',
            1 => 'Persiapan pelaksanaan identifikasi keberterimaan produk/jasa di pasar.',
            2 => 'Telah dilakukan identifikasi keberterimaan produk/jasa di pasar.',
            3 => 'Hasil identifikasi keberterimaan produk/jasa di pasar telah dianalisis.',
            4 => 'Hasil identifikasi keberterimaan produk/jasa di pasar telah dianalisis',
            5 => 'Hasil analisi identifikasi keberterimaan produk/jasa di pasar, telah menjadi pertimbangan dalam penyusunan strategi pemasaran',
        ],
        18 => [
            0 => 'Tidak melihat jaringan mitra sebagai hal yang strategis untuk keberhasilan bisnisnya.',
            1 => 'Mulai muncul kesadaran bahwa membangun kerjasama didalam jejaring secara dinamis adalah hal yang strategis untuk keberhasilan bisnisnya.',
            2 => 'Mulai melakukan pencarian jejaring yang dapat mendukung bisnisnya.',
            3 => 'Telah ditemukan dan mulai membangun kerjasama didalam jejaring yang dapat mendukung bisnisnya.',
            4 => 'Telah melakukan dan memanfaatkan kerjasama didalam jejaring namun belum dinamis',
            5 => 'Telah melakukan dan memanfaatkan kerjasama didalam jejaring secara dinamis',
        ],
        19 => [
            0 => 'Kerjasama yang telah dibangun, tetapi tidak ada tindak lanjutnya.',
            1 => 'Masih tahap perencanaan implementasi kerjasama.',
            2 => 'Telah ada rencana implementasi kerjasama yang disepakati, tetapi implementasinya masih nol.',
            3 => 'Telah diimplementasikan sebagian rencana kerjasama yang disepakati',
            4 => 'Telah mengimplementasikan seluruh rencana kerjasama yang disepakati.',
            5 => 'Telah mengimplementasikan seluruh rencana kerjasama yang disepakati, dan melakukan pengelolaan kerjasama yang sudah berjalan.',
        ],
        20 => [
            0 => 'Belum ada rencana pengendalian risiko non teknologi pada tahap introduksi produk ke pasar.',
            1 => 'Memiliki rencana dan persiapan pengendalian risiko non teknologi pada tahap introduksi produk ke pasar.',
            2 => 'Mulai menyusun rencana pengendalian risiko non teknologi pada tahap introduksi produk ke pasar.',
            3 => 'Tahap penyelesaian penyusunan rencana pengendalian risiko non teknologi pada tahap introduksi produk ke pasar.',
            4 => 'Tersusun rencana pengendalian risiko non teknologi pada tahap introduksi produk ke pasar.',
            5 => 'Rencana pengendalian risiko non teknologi pada tahap introduksi produk ke pasar telah divalidasi.',
        ],
        21 => [
            0 => 'Belum dilakukan kajian risiko organisasi (khususnya indikator keuangan) pada tahap introduksi produk ke pasar.',
            1 => 'Persiapan pelaksanaan kajian risiko organisasi (khususnya indikator keuangan) pada tahap introduksi produk ke pasar.',
            2 => 'Konsep dan outline pelaksanaan kajian risiko organisasi (khususnya indikator keuangan) pada tahap introduksi produk ke pasar telah disusun.',
            3 => 'Mulai dilakukan kajian risiko organisasi (khususnya indikator keuangan) pada tahap introduksi produk ke pasar.',
            4 => 'Hasil kajian risiko organisasi (khususnya indikator keuangan) pada tahap introduksi produk ke pasar selesai disusun.',
            5 => 'Telah diperoleh hasil kajian risiko organisasi (khususnya indikator keuangan) pada tahap introduksi produk ke pasar yang tervalidasi.',
        ],
        22 => [
            0 => 'Belum dilakukan kajian risiko dampak sosial pada tahap pengenalan produk ke pasa.',
            1 => 'Persiapan pelaksanaan kajian risiko dampak sosial pada tahap introduksi produk ke pasar.',
            2 => 'Konsep dan outline kajian risiko dampak sosial tahap introduksi produk ke pasar telah disusun.',
            3 => 'Mulai dilakukan kajian risiko dampak sosial pada tahap introduksi produk ke pasar.',
            4 => 'Kajian risiko dampak sosial pada tahap introduksi produk ke pasar selesai disusun.',
            5 => 'Hasil kajian risiko dampak sosial pada tahap introduksi produk ke pasar telah divalidasi.',
        ],
    ],

    // INDIKATOR 5
    5 => [
        1 => [
            0 => 'Belum menganggap garansi sebagai upaya perlindungan konsumen dan alat promosi yang efektif.',
            1 => 'Mulai muncul kesadaran kolektif dari produsen untuk memberikan garansi kepada konsumen.',
            2 => 'Tahap pengkajian pemberian garansi kepada konsumen.',
            3 => 'Telah memberikan garansi resmi berupa garansi service gratis.',
            4 => 'Telah memberikan garansi resmi berupa garansi service gratis dan penggantian spare part.',
            5 => 'Telah menyediakan garansi resmi secara penuh (garansi service gratis, penggantian spare part, penggantian unit baru) sebagai upaya perlindungan konsumen dan alat promosi yang efektif.',
        ],
        2 => [
            0 => 'HP Tidak tersedia pusat pelayanan purna jual, baik selama garansi maupun pasca garansi.',
            1 => 'Persiapan penyediaan pusat pelayanan purna jual, baik selama garansi maupun pasca garansi.',
            2 => 'Mulai tersedia secara sentralistik (di kantor induk produsen) pusat pelayanan purna jual, baik selama garansi maupun pasca garansi.',
            3 => 'Tersedia pusat pelayanan purna jual, baik selama garansi maupun pasca garansi, di kota dimana produsen berada.',
            4 => 'Tersedia pusat pelayanan purna jual, baik selama garansi maupun pasca garansi, di beberapa kota besar.',
            5 => 'Tersedia pusat pelayanan purna jual, baik selama garansi maupun pasca garansi, di seluruh kota besar.',
        ],
        3 => [
            0 => 'Tidak tersedia pasokan suku cadang untuk produk teknologi.',
            1 => 'Persiapan penyediaan pasokan suku cadang untuk produk teknologi.',
            2 => 'Mulai tersedia secara sentralistik (di kantor induk produsen) pasokan suku cadang untuk produk teknologi.',
            3 => 'Tersedia pasokan suku cadang untuk produk teknologi, melalui pusat pelayanan purna jual dan distributor di kota dimana produsen berada.',
            4 => 'Tersedia pasokan suku cadang untuk produk teknologi, melalui pusat pelayanan purna jual dan distributor di beberapa kota besar.',
            5 => 'Tersedia pasokan suku cadang untuk produk teknologi, melalui pusat pelayanan purna jual dan distributor di seluruh kota besar.',
        ],
        4 => [
            0 => 'Tidak lagi melakukan pengembangan.',
            1 => 'Belum ada pengembangan yang berarti, hanya perbaikan mutu melalui mekanisme Jaminan Mutu selama produksi.',
            2 => 'Aktivitas tidak hanya perbaikan mutu melalui mekanisme Jaminan Mutu selama produksi.',
            3 => 'Telah dilakukan aktivitas pengembangan berkelanjutan dalam rangka upaya menjawab keluhan pelanggan melalui perbaikan mutu produk sesuai permintaan pelanggan.',
            4 => 'Telah dilakukan aktivitas pengembangan berkelanjutan dalam upaya menjawab keluhan pelanggan melalui perbaikan mutu dan fungsi produk.',
            5 => 'Telah dilakukan aktivitas pengembangan berkelanjutan dalam upaya menjawab keluhan pelanggan melalui perbaikan mutu, fungsi, dan unjuk kerja produk.',
        ],
        5 => [
            0 => 'Surat garansi produk/teknologi yang dipasarkan.',
            1 => 'Daftar komponen produk/teknologi yang mudah aus atau rusak.',
            2 => 'Daftar suku cadang yang harus disediakan untuk mendukung layanan purna jual.',
            3 => 'Daftar layanan teknis yang harus disediakan untuk mendukung layanan purna jual.',
            4 => 'Daftar lokasi layanan purna jual.',
            5 => 'Informasi lokasi layanan purna jual, akses layanan, fasilitas layanan, akuntablitas jasa layanan, ketersediaan produk dan kompetensi sumberdaya manusia berbasis kebutuhan produk.',
        ],
        6 => [
            0 => 'Tidak dilakukan diferensiasi produk.',
            1 => 'Ada rencana srataegi diferensiasi produk.',
            2 => 'Rencana strategi diferensiasi produk telah disusun.',
            3 => 'Strategi diferensiasi produk mulai diterapkan.',
            4 => 'Perusahaan belum optimal menerapkan strategi diferensiasi produk.',
            5 => 'Perusahaan melaksanakan strategi diferensiasi produk secara optimal.',
        ],
        7 => [
            0 => 'Tidak dilakukan evaluasi dan penyempurnaan model bisnis.',
            1 => 'Tahap perencanaan evaluasi dan penyempurnaan model bisnis.',
            2 => 'Mulai dilakukan evaluasi dan penyempurnaan model bisnis model bisnis.',
            3 => 'Diperoleh hasil evaluasi dan tahap penyempurnaan model bisnis.',
            4 => 'Telah dilakukan penyempurnaan model bisnis berdasar hasil evaluasi.',
            5 => 'Penyempurnaan model bisnis telah diverifikasi dan divalidasi.',
        ],
        8 => [
            0 => 'Kemitraan belum dipertimbangkan sebagai faktor yang mempengaruhi daya saing.',
            1 => 'Telah memiliki rencana strategis kemitraan usaha',
            2 => 'Rencana strategi kemitraan telah diimplementasikan tetapi belum optimal',
            3 => 'Kemitraan telah dioptimalkan untuk aspek teknis (pengembangan produk, perbaikan proses produksi, perbaikan kualitas, dan akses teknologi).',
            4 => 'Kemitraan dioptimalkan untuk aspek ekspansi pasar, distribusi, pemasok bahan baku, peningkatan profit dan akuisisi pelanggan baru.',
            5 => 'Kemitraan telah terjalin di berbagai aspek dari hulu ke hilir dengan saling menguntungkan.',
        ],
        9 => [
            0 => 'Belum ada upaya meningkatkan efektivitas dan kerjasama organisasi.',
            1 => 'Mulai muncul kesadaran upaya peningkatan efektivitas dan kerjasama organisasi.',
            2 => 'Secara sadar melakukan upaya peningkatan efektivitas & kerjasama organisasi.',
            3 => 'Telah dilakukan peningkatan efektivitas & kerjasama organisasi sehingga terpenuhi pencapaian visi organisasi, pengembangan sumber daya manusia organisasi, dan pemenuhan aspirasi.',
            4 => 'Telah dilakukan peningkatan efektivitas dan kerjasama organisasi sehingga terpenuhi pencapaian visi organisasi, pengembangan SDM organisasi, pemenuhan aspirasi & menghasilkan keuntungan bagi organisasi.',
            5 => 'Terpenuhi pencapaian visi organisasi, pengembangan SDM organisasi, pemenuhan aspirasi, menghasilkan keuntungan bagi organisasi, kepuasan pelanggan & memberikan dampak positif bagi masyarakat di luar organisasi.',
        ],
        10 => [
            0 => 'Tidak ada upaya melakukan restrukturisasi yang dibutuhkan.',
            1 => 'Mulai ada kesadaran dibutuhkan restrukturisasi di perusahaan.',
            2 => 'Perusahaan mempersiapkan restrukturisasi yang dibutuhkan.',
            3 => 'Perusahaan mulai menjalankan restrukturisasi yang dibutuhkan, dimulai dengan evaluasi kinerja.',
            4 => 'Perusahaan telah melakukan evaluasi kinerja dan melakukan beberapa perbaikan dalam pelaksanaan restrukturisasi yang dibutuhkan.',
            5 => 'Melakukan restrukturisasi yang dibutuhkan, melalui evaluasi kinerjanya serta melakukan serangkaian perbaikan berkelanjutan agar tetap tumbuh dan dapat bersaing.',
        ],
        11 => [
            0 => 'Belum diidentifikasi peningkatan peluang mempertemukan produk teknologi dengan kebutuhan pasar.',
            1 => 'Telah dipersiapkan pelaksanaan identifikasi peningkatan peluang mempertemukan produk teknologi dengan kebutuhan pasar.',
            2 => 'Mulai dilakukan identifikasi peningkatan peluang mempertemukan produk teknologi dengan kebutuhan pasar',
            3 => 'Telah dapat diidentifikasi peningkatan peluang pasar baru yang dapat dimasuki.',
            4 => 'Telah dapat diidentifikasi peningkatan peluang pasar baru yang dapat dimasuki dan pelanggan baru dalam pasar yang ada sekarang.',
            5 => 'Telah dapat diidentifikasi peningkatan peluang mempertemukan produk teknologi dengan kebutuhan pasar, yaitu berupa pasar baru yang dapat dimasuki, pelanggan baru dalam pasar yang ada sekarang, dan produk-produk baru yang mempunyai potensi.',
        ],
        12 => [
            0 => 'Belum dilakukan review proses teknis dan komersial.',
            1 => 'Persiapan dilakukan review proses teknis dan komersial.',
            2 => 'Telah dilakukan review proses teknis dan komersial untuk meningkatkan efektivitas.',
            3 => 'Telah dilakukan review proses teknis dan komersial untuk meningkatkan efektivitas dan efisiensi.',
            4 => 'Telah dilakukan review proses teknis dan komersial untuk meningkatkan efektivitas, efisiensi, dan produktivitas.',
            5 => 'Telah diperoleh dan digunakan hasil review proses teknis dan komersial untuk meningkatkan efektivitas, efisiensi, produktivitas, dan profit.',
        ],
        13 => [
            0 => 'Belum menerapkan Lean Manufacturing secara total.',
            1 => 'Persiapan di tingkat top management untuk menerapkan Lean Manufacturing secara total.',
            2 => 'Tahap awal penerapan Lean Manufacturing secara total.',
            3 => 'Tahap awal penerapan Lean Manufacturing secara total.',
            4 => 'Proses iterasi penerapan Lean Manufacturing secara total.',
            5 => 'Telah diterapkan Lean Manufacturing secara total, dan telah diperoleh manfaat bagi perusahaan dan konsumen.',
        ],
        14 => [
            0 => 'Dalam perbaikan kinerja belum dibutuhkan masukan (internal/eksternal) kepada manajemen.',
            1 => 'Mulai ada kebutuhan masukan (internal maupun eksternal) kepada manajemen untuk perbaikan kinerja.',
            2 => 'Telah dilakukan masukan internal secara terbatas kepada manajemen untuk perbaikan kinerja.',
            3 => 'Telah dilakukan masukan internal 360 derajat kepada manajemen untuk perbaikan kinerja.',
            4 => 'Telah dilakukan masukan internal 360 derajat dan eksternal (mikro) kepada manajemen untuk perbaikan kinerja.',
            5 => 'Telah dilakukan masukan internal 360 derajat dan eksternal (mikro dan makro) kepada manajemen untuk perbaikan kinerja.',
        ],
        15 => [
            0 => 'Belum menerapkan penjaminan mutu sesuai standar (SNI) secara intensif.',
            1 => 'Telah muncul kesadaran menerapkan penjaminan mutu sesuai standar (SNI).',
            2 => 'Upaya sosialisasi penerapan penjaminan mutu sesuai standar (SNI).',
            3 => 'Mulai mempersiapkan penerapan penjaminan mutu sesuai standar (SNI).',
            4 => 'Telah menerapkan penjaminan mutu sesuai standar (SNI), namun belum intensif.',
            5 => 'Telah menerapkan penjaminan mutu sesuai standar (SNI) secara intensif, dan telah digunakan sebagai alat bagi manajemen.',
        ],
        16 => [
            0 => 'Belum ada jaminan terhadap mutu, keamanan dan keselamatan produk yang dimanfaatkan oleh masyarakat.',
            1 => 'Membangun kesadaran dan komitmen.',
            2 => 'Sosialisasi rencana pelaksanaan sertifikasi produk dan akreditasi lembaga.',
            3 => 'Persiapan administrasi dan teknis pelaksanaan sertifikasi produk dan akreditasi lembaga.',
            4 => 'Proses sertifikasi produk dan akreditasi lembaga.',
            5 => 'Telah mendapat sertifikat produk dan akreditasi lembaga sebagai bentuk jaminan terhadap mutu, keamanan dan keselamatan produk di masyarakat.',
        ],
        17 => [
            0 => 'Tidak dilakukan identifikasi kebutuhan memperluas pasar.',
            1 => 'Persiapan untuk melakukan identifikasi kebutuhan memperluas pasar.',
            2 => 'Dalam proses penyelesaian identifikasi kebutuhan memperluas pasar.',
            3 => 'Dalam proses penyelesaian identifikasi kebutuhan ekspansi pasar.',
            4 => 'Identifikasi kebutuhan ekspansi pasar telah selesai.',
            5 => 'Hasil identifikasi kebutuhan ekspansi pasar telah divalidasi.',
        ],
        18 => [
            0 => 'Belum ada peningkatan kapasitas produksi.',
            1 => 'Terdapat kecenderungan meningkatnya permintaan pasar.',
            2 => 'Ada peningkatan kapasitas produksi namun belum tercapai kapasitas produksi optimumnya.',
            3 => 'Ada peningkatan kapasitas produksi, dan telah tercapai kapasitas produksi optimumnya.',
            4 => 'Ada keharuskan penambahan kapasitas produksi.',
            5 => 'Telah dilakukan penambahan kapasitas produksi atas permintaan pasar.',
        ],
        19 => [
            0 => 'Belum dilakukan peningkatan kerjasama didalam jejaring secara dinamis.',
            1 => 'Upaya evaluasi terhadap kerjasama didalam jejaring yang telah berjalan.',
            2 => 'Telah ditetapkan ada kebutuhan peningkatan kerjasama didalam jejaring yang telah berjalan.',
            3 => 'Telah dilakukan upaya peningkatan kerjasama didalam jaringan produksi.',
            4 => 'Telah dilakukan upaya peningkatan kerjasama didalam jaringan produksi dan pemasaran.',
            5 => 'Telah di upayakan peningkatan kerjasama dalam jejaring secara dinamis, meliputi: jaringan produksi, jaringan pemasaran, maupun jaringan pelayanan.',
        ],
        20 => [
            0 => 'Belum dilakukan peningkatan mutu pengelolaan kerjasama yang sudah berjalan.',
            1 => 'Evaluasi terhadap pengelolaan kerjasama yang telah berjalan.',
            2 => 'Telah teridentifikasi beberapa kelemahan pengelolaan kerjasama yang telah berjalan.',
            3 => 'Perencanaan upaya peningkatan mutu pengelolaan kerjasama yang sudah berjalan.',
            4 => 'Dilakukan eksekusi upaya peningkatan mutu pengelolaan kerjasama yang sudah berjalan.',
            5 => 'Telah dilakukan peningkatan mutu pengelolaan kerjasama yang sudah berjalan meliputi prinsip: persamaan, keterbukaan dan saling menguntungkan.',
        ],
        21 => [
            0 => 'Belum dilakukan kerjasama distribusi dan pemasaran produk dengan pihak lain.',
            1 => 'Identifikasi mitra potensi untuk kerjasama distribusi dan pemasaran produk.',
            2 => 'Telah tetapkan mitra untuk kerjasama distribusi dan pemasaran produk.',
            3 => 'Perjanjian kesepakatan kerjasama distribusi dan pemasaran produk.',
            4 => 'Eksekusi kerjasama distribusi dan pemasaran produk.',
            5 => 'Telah berjalan kerjasama distribusi dan pemasaran produk dengan mitra, sehingga jangkauan pasarnya menjadi lebih luas.',
        ],
        22 => [
            0 => 'Belum disusun rencana pengendalian risiko non teknologi pada tahap kematangan pasar tercapai.',
            1 => 'Garis besar rencana penyusunan risiko non-teknologi telah selesai pada tahap kematangan pasar tercapai.',
            2 => 'Persiapan penyusunan rencana pengendalian risiko non teknologi pada tahap kematangan pasar tercapai.',
            3 => 'Sedang disusun rencana pengendalian risiko non teknologi pada tahap kematangan pasar tercapai.',
            4 => 'Penyelesaian penyusunan rencana pengendalian risiko non teknologi pada tahap kematangan pasar tercapai.',
            5 => 'Tersusun rencana pengendalian risiko non teknologi pada tahap kematangan pasar tercapai.',
        ],
        23 => [
            0 => 'Belum dilakukan kajian risiko organisasi (khususnya indikator keuangan) pada tahap kematangan pasar tercapai.',
            1 => 'Outline penyusunan kajian risiko organisasi (khususnya indikator keuangan) telah disusun pada tahap kematangan pasar tercapai.',
            2 => 'Persiapan dilakukan kajian risiko organisasi (khususnya indikator keuangan) pada tahap kematangan pasar tercapai.',
            3 => 'Tahap penyelesaian kajian risiko organisasi (khususnya indikator keuangan) pada tahap kematangan pasar tercapai.',
            4 => 'Diperoleh hasil kajian risiko organisasi (khususnya indikator keuangan) pada tahap kematangan pasar tercapai.',
            5 => 'Tersusun kajian risiko organisasi (khususnya indikator keuangan) pada tahap kematangan pasar tercapai.',
        ],
        24 => [
            0 => 'Belum dilakukan kajian risiko dampak sosial.',
            1 => 'Garis besar penyusunan kajian risiko dampak sosial telah selesai.',
            2 => 'Persiapan dilakukan kajian risiko dampak sosial pada tahap kematangan pasar tercapai.',
            3 => 'Tahap penyelesaian kajian risiko dampak sosial pada tahap kematangan pasar tercapai.',
            4 => 'Diperoleh hasil kajian risiko dampak sosial pada tahap kematangan pasar tercapai.',
            5 => 'Tersusun kajian risiko dampak sosial pada tahap kematangan pasar tercapai.',
        ],
    ],

    // INDIKATOR 6
    6 => [
        1 => [
            0 => 'Belum dilakukan review terhadap produk teknologi milik kompetitor.',
            1 => 'Pembahasan urgensi review terhadap produk milik kompetitor di level top management.',
            2 => 'Persiapan pelaksanaan review terhadap produk milik kompetitor di level top management.',
            3 => 'Mulai dilakukan review terhadap produk milik kompetitor di level top management.',
            4 => 'Review terhadap produk milik kompetitor dalam penyelesaian.',
            5 => 'Telah diperoleh hasil review terhadap produk teknologi milik kompetitor.',
        ],
        2 => [
            0 => 'Belum dilakukan review terhadap kemampuan teknologi yang dimiliki.',
            1 => 'Pembahasan ditingkat top management terkait urgensi review.',
            2 => 'Persiapan pelaksanaan review terhadap kemampuan teknologi yang dimiliki.',
            3 => 'Mulai dilakukan review terhadap kemampuan teknologi.',
            4 => 'Review terhadap kemampuan teknologi dalam penyelesaian.',
            5 => 'Telah diperoleh review kemampuan teknologi.',
        ],
        3 => [
            0 => 'Belum diputuskan apakah melakukan inovasi ulang, atau pengembangan produk baru.',
            1 => 'Keputusan melakukan kajian untuk menentukan pilihan: inovasi ulang atau pengembangan produk baru.',
            2 => 'Persiapan pelaksanaan kajian untuk menentukan pilihan: inovasi ulang atau pengembangan produk baru.',
            3 => 'Mulai dilaksanaan kajian untuk menentukan pilihan: inovasi ulang atau pengembangan produk baru.',
            4 => 'Kajian untuk menentukan pilihan: inovasi ulang atau pengembangan produk baru dalam penyelesaian.',
            5 => 'Telah ada keputusan dari menejemen terkait pilihan atas inovasi ulang atau pengembangan baru.',
        ],
        4 => [
            0 => 'Penurunan pasar belum dikonfirmasi.',
            1 => 'Terdapat gejala kecenderungan (trend) penurunan pasar.',
            2 => 'Gejala kecenderungan (trend) penurunan pasar sedang dianalisis.',
            3 => 'Penurunan pasar mulai terkonfirmasi berdasarkan hasil analisis.',
            4 => 'Penurunan pasar terkonfirmasi berdasarkan hasil analisis.',
            5 => 'Penurunan pasar telah dikonfirmasi secara faktual.',
        ],
        5 => [
            0 => 'Belum ada riset pasar untuk persetujuan inovasi ulang atau pengembangan teknologi yang lebih maju.',
            1 => 'Persiapan pelaksanaan riset pasar untuk persetujuan inovasi ulang atau pengembangan teknologi yang lebih maju.',
            2 => 'Mulai dilaksanakan riset pasar untuk persetujuan inovasi ulang atau pengembangan teknologi yang lebih maju.',
            3 => 'Sedang dilaksanakan riset pasar untuk persetujuan inovasi ulang atau pengembangan teknologi yang lebih maju.',
            4 => 'Riset pasar untuk persetujuan inovasi ulang atau pengembangan teknologi yang lebih maju selesai dilaksanakan.',
            5 => 'Hasil riset pasar menjadi pertimbangan bagi Top Management.',
        ],
        6 => [
            0 => 'Belum meninjau permintaan pasar.',
            1 => 'Telah menyusun konsep review permintaan pasar.',
            2 => 'Persiapan review permintaan pasar.',
            3 => 'Mulai pelaksanaan review permintaan pasar.',
            4 => 'Telah diperoleh hasil review permintaan pasar.',
            5 => 'Hasil review permintaan pasar menjadi pertimbangan top manajemen mengambil keputusan untuk reinovasi.',
        ],
        7 => [
            0 => 'Belum diidentifikasi peluang tumbuhnya pasar atau ekspansi pasar baru.',
            1 => 'Persiapan identifikasi peluang tumbuhnya pasar atau ekspansi pasar baru.',
            2 => 'Mulai dilakukan identifikasi peluang tumbuhnya pasar atau ekspansi pasar baru.',
            3 => 'Tahap penyelesaian identifikasi peluang tumbuhnya pasar atau ekspansi pasar baru.',
            4 => 'Telah diperoleh hasil identifikasi peluang tumbuhnya pasar atau ekspansi pasar baru.',
            5 => 'Hasil identifikasi peluang tumbuhnya pasar atau ekspansi pasar baru menjadi pertimbangan top manajemen mengambil keputusan untuk reinovasi.',
        ],
        8 => [
            0 => 'Tidak ada dukungan komitmen manajemen dan dukungan sumber daya di lingkungan perusahaan.',
            1 => 'Organisasi belum mempunyai arah dan aksi nyata dalam mendukung Inovasi Ulang atau Pengembangan Teknologi Baru.',
            2 => 'Organisasi telah memberikan arah, tetapi perannya belum nyata dalam mendukung Inovasi Ulang atau Pengembangan Teknologi Baru.',
            3 => 'Ada peran organisasi dalam bentuk dukungan sumber daya di lingkungan perusahaan.',
            4 => 'Ada peran organisasi dalam bentuk dukungan nyata berupa komitmen manajemen di lingkungan perusahaan.',
            5 => 'Ada peran organisasi dalam bentuk dukungan nyata berupa komitmen manajemen dan dukungan sumber daya di lingkungan perusahaan.',
        ],
        9 => [
            0 => 'Tidak memiliki jejaring untuk mendukung Inovasi Ulang atau Pengembangan Teknologi Baru.',
            1 => 'Memiliki jejaring, tetapi belum ada peran dalam mendukung Inovasi Ulang atau Pengembangan Teknologi Baru.',
            2 => 'Memiliki jejaring dan perannya kurang dalam mendukung Inovasi Ulang atau Pengembangan Teknologi Baru.',
            3 => 'Memiliki jejaring dan ada peran yang cukup besar dalam mendukung Inovasi Ulang atau Pengembangan Teknologi Baru.',
            4 => 'Memiliki jejaring dan ada peran yang besar dalam mendukung Inovasi Ulang atau Pengembangan Teknologi Baru.',
            5 => 'Memiliki jejaring dan ada peran yang sangat besar dalam mendukung Inovasi Ulang atau Pengembangan Teknologi Baru.',
        ],
        10 => [
            0 => 'Inovasi produksi atau pengembangan teknologi produksi baru belum menjadi kebutuhan bagi perusahaan.',
            1 => 'Mulai muncul tekanan dari pesaing di pasar yang ditunjukkan oleh penurunan penjualan.',
            2 => 'Perusahaan mulai melakukan upaya mencari berbagai alternatif untuk bertahan.',
            3 => 'Alternatif inovasi produksi atau pengembangan teknologi produksi baru belum menjadi prioritas.',
            4 => 'Alternatif inovasi produksi atau pengembangan teknologi produksi baru dipertimbangkan sebagai prioritas.',
            5 => 'Inovasi produksi atau pengembangan teknologi produksi baru telah diputuskan menjadi kebutuhan mendesak bagi perusahaan.',
        ],
        11 => [
            0 => 'Belum diidentifikasi inovasi lanjutan terkait skema investasi tambahan.',
            1 => 'Persiapan identifikasi inovasi lanjutan terkait skema investasi tambahan.',
            2 => 'Mulai dilakukan identifikasi inovasi lanjutan terkait skema investasi tambahan.',
            3 => 'Tahap penyelesaian identifikasi inovasi lanjutan terkait skema investasi tambahan.',
            4 => 'Telah diperoleh hasil identifikasi inovasi lanjutan terkait skema investasi tambahan.',
            5 => 'Hasil identifikasi inovasi lanjutan menjadi pertimbangan top manajemen mengambil keputusan untuk reinvestasi.',
        ],
        12 => [
            0 => 'Belum dilakukan review terhadap kemitraan yang sudah berjalan.',
            1 => 'Pada tahap persiapan pelaksanaan review terhadap kemitraan yang sudah berjalan.',
            2 => 'Mulai dilakukan review terhadap kemitraan yang sudah berjalan.',
            3 => 'Dalam proses penyelesaian review terkait dengan mutu mitra dan kemitraan yang sudah berjalan.',
            4 => 'Telah diperoleh hasil review terkait dengan mutu mitra dan kemitraan yang sudah berjalan.',
            5 => 'Telah diketahui kualitas, kelebihan serta kekurangan dari kemitraan yang sudah berjalan.',
        ],
        13 => [
            0 => 'Belum melakukan pencarian mitra potensial untuk mendukung Inovasi ulang atau Pengembangan Teknologi Baru.',
            1 => 'Identifikasi kebutuhan Inovasi ulang atau Pengembangan Teknologi Baru.',
            2 => 'Evaluasi kemampuan internal dalam pelaksanaan Inovasi ulang atau Pengembangan Teknologi Baru.',
            3 => 'Identifikasi mitra potensial untuk mendukung Inovasi ulang atau Pengembangan Teknologi Baru.',
            4 => 'Telah ditetapkan kebutuhan dan peran mitra potensial untuk mendukung Inovasi ulang atau Pengembangan Teknologi Baru.',
            5 => 'Telah diperoleh mitra potensial untuk mendukung Inovasi ulang atau Pengembangan Teknologi Baru.',
        ],
        14 => [
            0 => 'Belum dilakukan kajian risiko untuk mendukung keputusan Inovasi Ulang atau Pengembangan Teknologi Baru.',
            1 => 'Persiapan pelaksanaan kajian risiko untuk mendukung keputusan Inovasi Ulang atau Pengembangan Teknologi Baru.',
            2 => 'Mulai dilaksanakan kajian risiko untuk mendukung keputusan Inovasi Ulang atau Pengembangan Teknologi Baru.',
            3 => 'Sedang dilaksanakan kajian risiko untuk mendukung keputusan Inovasi Ulang atau Pengembangan Teknologi Baru.',
            4 => 'Selesai dilaksanakan kajian risiko untuk mendukung keputusan Inovasi Ulang atau Pengembangan Teknologi Baru.',
            5 => 'Hasil analisis kajian risiko menjadi pertimbangan bagi top manajemen untuk mengambil keputusan melakukan Inovasi Ulang atau Pengembangan Teknologi Baru.',
        ],
    ],

];
