<?php

return [
    // INDIKATOR 1 - Total 22 rows
    1 => [
        ['no' => 1, 'aspect' => 'T', 'desc' => 'Ide baru yang memberi solusi permasalahan masyarakat'],
        ['no' => 2, 'aspect' => 'T', 'desc' => 'Telah dilakukan pengamatan prinsip-prinsip ilmiah dasar dan publikasi ilmiah'],
        ['no' => 3, 'aspect' => 'T', 'desc' => 'Faktor yang membedakan temuan dengan temuan lain dan unsur kebaruan dari sebuah ide atau gagasan telah diidentifikasi'],
        ['no' => 4, 'aspect' => 'T', 'desc' => 'Mengidentifikasi tahapan riset dan targetnya'],
        ['no' => 5, 'aspect' => 'T', 'desc' => 'Teknologi yang akan dikembangkan telah layak secara ilmiah (scientific feasibility)'],
        ['no' => 6, 'aspect' => 'M', 'desc' => 'Inovasi dilakukan berdasarkan permintaan dan/atau kebutuhan pelanggan'],
        ['no' => 7, 'aspect' => 'M', 'desc' => 'Permintaan dan kebutuhan pelanggan telah diidentifikasi'],
        ['no' => 8, 'aspect' => 'M', 'desc' => 'Telah mengidentifikasikan lokasi pasar yang akan dituju'],
        ['no' => 9, 'aspect' => 'O', 'desc' => 'Telah memiliki strategi inovasi'],
        ['no' => 10, 'aspect' => 'O', 'desc' => 'Lingkup proyek dan tugas telah diidentifikasi'],
        ['no' => 11, 'aspect' => 'O', 'desc' => 'Kebutuhan akan sumber daya, dana dan fasilitas penelitian telah dikonfirmasi'],
        ['no' => 12, 'aspect' => 'O', 'desc' => 'Tersedia saluran komunikasi tanpa hambatan'],
        ['no' => 13, 'aspect' => 'Mf', 'desc' => 'Konsekuensi hasil temuan telah diidentifikasi melalui dasar manufaktur ekonomis'],
        ['no' => 14, 'aspect' => 'Mf', 'desc' => 'Teridentifikasi dalam konsep manufaktur secara teknis dan ekonomis'],
        ['no' => 15, 'aspect' => 'Mf', 'desc' => 'Tersedia bukti konsep manufaktur melalui analitik atau eksperimen laboratorium'],
        ['no' => 16, 'aspect' => 'I', 'desc' => 'Ide yang dikembangkan memiliki konsep model bisnis'],
        ['no' => 17, 'aspect' => 'I', 'desc' => 'Peluang investasi untuk mewujudkan hasil temuan telah diidentifikasi'],
        ['no' => 18, 'aspect' => 'I', 'desc' => 'Kebutuhan pembiayaan telah terestimasi'],
        ['no' => 19, 'aspect' => 'P', 'desc' => 'Terbuka peluang kerjasama dengan industri atau institusi lain'],
        ['no' => 20, 'aspect' => 'P', 'desc' => 'Tersedia atau dapat dipersiapkan perjanjian kerjasama'],
        ['no' => 21, 'aspect' => 'R', 'desc' => 'Tersedia atau dapat disiapkan strategi manajemen risiko'],
        ['no' => 22, 'aspect' => 'R', 'desc' => 'Risiko secara keseluruhan teridentifikasi'],
    ],
    
    // INDIKATOR 2 - Total 21 rows
    2 => [
        ['no' => 1, 'aspect' => 'T', 'desc' => 'Telah melakukan validasi terhadap komponen individu dari teknologi'],
        ['no' => 2, 'aspect' => 'T', 'desc' => 'Prototipe telah didemonstrasikan dalam lingkungan yang relevan'],
        ['no' => 3, 'aspect' => 'T', 'desc' => 'Teknologi dinyatakan layak secara teknis'],
        ['no' => 4, 'aspect' => 'T', 'desc' => 'Telah melakukan pendaftaran kekayaan intelektual (misal: paten, desain industri, hak cipta, merek, dll)'],
        ['no' => 5, 'aspect' => 'T', 'desc' => 'Secara teknis mampu memberikan solusi terhadap permasalahan yang dihadapi masyarakat'],
        ['no' => 6, 'aspect' => 'M', 'desc' => 'Pelanggan akhir teridentifikasi'],
        ['no' => 7, 'aspect' => 'M', 'desc' => 'Telah mengeluarkan rencana peluncuran produk baru ke pasar secara rinci'],
        ['no' => 8, 'aspect' => 'M', 'desc' => 'Telah memulai kesiapan modal intelektual (intellectual capital)'],
        ['no' => 9, 'aspect' => 'O', 'desc' => 'Analisis dan rencana bisnis telah dikeluarkan'],
        ['no' => 10, 'aspect' => 'O', 'desc' => 'Telah memiliki keterlibatan dengan individu kunci'],
        ['no' => 11, 'aspect' => 'O', 'desc' => 'Telah melakukan persetujuan persyaratan proyek dan daftar mitra proyek'],
        ['no' => 12, 'aspect' => 'O', 'desc' => 'Telah melakukan persetujuan tanggung jawab dan persetujuan batas waktu dalam pengelolaan suatu proyek'],
        ['no' => 13, 'aspect' => 'Mf', 'desc' => 'Identifikasi teknologi dan komponen kritikal telah komplit'],
        ['no' => 14, 'aspect' => 'Mf', 'desc' => 'Material, perkakas dan alat uji prototipe, maupun keahlian personel telah diperlihatkan oleh sub system/system dalam suatu lingkungan produksi yang relevan'],
        ['no' => 15, 'aspect' => 'I', 'desc' => 'Keunggulan jual yang dimiliki telah teruji kepada pelanggan'],
        ['no' => 16, 'aspect' => 'I', 'desc' => 'Solusi yang ditawarkan kepada pelanggan memunculkan daya tarik yang menguntungkan di pasar'],
        ['no' => 17, 'aspect' => 'I', 'desc' => 'Validasi value proposition, channel, segmen pelanggan, model hubungan dengan pelanggan yang ada, dan aliran revenue terbukti telah dilakukan'],
        ['no' => 18, 'aspect' => 'P', 'desc' => 'Telah melakukan penggalian informasi dan seleksi mitra'],
        ['no' => 19, 'aspect' => 'P', 'desc' => 'Pola kemitraan dibangun dengan tepat'],
        ['no' => 20, 'aspect' => 'R', 'desc' => 'Kajian risiko teknologi telah dilakukan dalam setiap langkah pengembangan teknologi'],
        ['no' => 21, 'aspect' => 'R', 'desc' => 'Pada tahap pengembangan teknologi dilakukan penyusunan rencana pengendalian risiko teknologi'],
    ],
    
    // INDIKATOR 3 - Total 21 rows
    3 => [
        ['no' => 1, 'aspect' => 'T', 'desc' => 'Sistem aktual teknologi telah didemonstrasikan dalam lingkungan yang sebenarnya'],
        ['no' => 2, 'aspect' => 'T', 'desc' => 'Uji eksternal dari teknologi yang dikembangkan telah dilakukan secara lengkap, dalam rangka memenuhi persyaratan teknis dan kesesuaian regulasi'],
        ['no' => 3, 'aspect' => 'T', 'desc' => 'Telah mendokumentasikan teknologi yang dikembangkan'],
        ['no' => 4, 'aspect' => 'T', 'desc' => 'Hasil Inovasi telah diperkenalkan'],
        ['no' => 5, 'aspect' => 'T', 'desc' => 'Telah memperoleh Kekayaan intelektual (misal: paten, desain industri, hak cipta, merek, dll)'],
        ['no' => 6, 'aspect' => 'M', 'desc' => 'Kebutuhan khusus dan keperluan pelanggan telah diketahui'],
        ['no' => 7, 'aspect' => 'M', 'desc' => 'Segmen, ukuran dan pangsa pasar telah diprediksi'],
        ['no' => 8, 'aspect' => 'M', 'desc' => 'Produk telah diperkenalkan, dan harganya telah ditetapkan'],
        ['no' => 9, 'aspect' => 'O', 'desc' => 'Penetapan organisasi (struktur bisnis dengan staff dan kolaborator)'],
        ['no' => 10, 'aspect' => 'O', 'desc' => 'Identifikasi beberapa tambahan staff yang dibutuhkan'],
        ['no' => 11, 'aspect' => 'O', 'desc' => 'Telah merincikan pembagian tanggung jawab dan beban kerja'],
        ['no' => 12, 'aspect' => 'Mf', 'desc' => 'Desain sistem sebagian besar stabil dan terbukti dalam uji dan evaluasi'],
        ['no' => 13, 'aspect' => 'Mf', 'desc' => 'Proses dan prosedur manufaktur terbukti dalam skala pilot'],
        ['no' => 14, 'aspect' => 'Mf', 'desc' => 'Produksi pada laju rendah telah dilaksanakan'],
        ['no' => 15, 'aspect' => 'I', 'desc' => 'Telah mendefinisikan kondisi akhir dari produk teknologi dengan mempertimbangkan target person, pasar vertikal, serta geografik'],
        ['no' => 16, 'aspect' => 'I', 'desc' => 'Validasi terhadap bisnis yang dilakukan sudah diterapkan'],
        ['no' => 17, 'aspect' => 'I', 'desc' => 'Identifikasi dan validasi terhadap indikator kinerja utama yang mengindikasikan keberhasilan bisnis'],
        ['no' => 18, 'aspect' => 'P', 'desc' => 'Telah terjalin kemitraan secara formal'],
        ['no' => 19, 'aspect' => 'P', 'desc' => 'Telah menyusun dan telah menerapkan rencana kerja sama'],
        ['no' => 20, 'aspect' => 'R', 'desc' => 'Kajian risiko teknologi menjadi dasar pengambilan keputusan teknis dalam tahap engineering & Operation'],
        ['no' => 21, 'aspect' => 'R', 'desc' => 'Pada tahap penerapan teknologi dilakukan penyusunan rencana pengendalian risiko teknologi'],
    ],
    
    // INDIKATOR 4 - Total 22 rows
    4 => [
        ['no' => 1, 'aspect' => 'T', 'desc' => 'Telah terbentuk keahlian terkait pengoperasian dan pemeliharaan produk teknologi'],
        ['no' => 2, 'aspect' => 'T', 'desc' => 'Penggunaan umum produk teknologi oleh cakupan pasar yang luas telah diidentifikasi'],
        ['no' => 3, 'aspect' => 'T', 'desc' => 'Keuntungan teknologi melalui hasil pengujian telah diidentifikasi'],
        ['no' => 4, 'aspect' => 'T', 'desc' => 'Adanya dukungan terhadap adopsi produk teknologi oleh pasar'],
        ['no' => 5, 'aspect' => 'M', 'desc' => 'Telah membangun citra produk teknologi kepada pasar'],
        ['no' => 6, 'aspect' => 'M', 'desc' => 'Model bisnis ditetapkan'],
        ['no' => 7, 'aspect' => 'M', 'desc' => 'Pesaing diidentifikasi dengan baik'],
        ['no' => 8, 'aspect' => 'M', 'desc' => 'Pemasaran ditekankan pada pengenalan secara spesifik produk teknologi kepada para pelanggannya'],
        ['no' => 9, 'aspect' => 'O', 'desc' => 'Telah menetapkan bentuk organisasi'],
        ['no' => 10, 'aspect' => 'O', 'desc' => 'Telah mengembangkan kemitraan dengan organisasi independen'],
        ['no' => 11, 'aspect' => 'O', 'desc' => 'Identifikasi peluang untuk memperkenalkan produk kepada mitra dan pasar baru'],
        ['no' => 12, 'aspect' => 'Mf', 'desc' => 'Telah diperlihatkan produksi yang menguntungkan secara finansial'],
        ['no' => 13, 'aspect' => 'Mf', 'desc' => 'Mulai menerapkan GMP (Good Manufacturing Practice) atau Lean Manufacturing'],
        ['no' => 14, 'aspect' => 'Mf', 'desc' => 'Mulai menerapkan jaminan mutu sesuai standar (SNI)'],
        ['no' => 15, 'aspect' => 'Mf', 'desc' => 'Adanya tuntutan masyarakat terhadap mutu, keamanan dan keselamatan produk yang dimanfaatkan'],
        ['no' => 16, 'aspect' => 'I', 'desc' => 'Potensi pasar teridentifikasi'],
        ['no' => 17, 'aspect' => 'I', 'desc' => 'Daya terima pasar terhadap produk telah teridentifikasi'],
        ['no' => 18, 'aspect' => 'P', 'desc' => 'Melakukan kerja sama di dalam jejaring usaha secara dinamis'],
        ['no' => 19, 'aspect' => 'P', 'desc' => 'Terus melakukan pengelolaan terhadap kerjasama yang sudah berjalan'],
        ['no' => 20, 'aspect' => 'R', 'desc' => 'Penyusunan rencana pengendalian risiko non teknologi (organisasi dan sosial) pada tahap pengenalan produk ke pasar'],
        ['no' => 21, 'aspect' => 'R', 'desc' => 'Kajian risiko organisasi (khususnya indikator keuangan) dilakukan pada tahap pengenalan produk ke pasar'],
        ['no' => 22, 'aspect' => 'R', 'desc' => 'Kajian risiko dampak sosial pada tahap pengenalan produk ke pasar'],
    ],
    
    // INDIKATOR 5 - Total 24 rows
    5 => [
        ['no' => 1, 'aspect' => 'T', 'desc' => 'Adanya garansi terhadap produk teknologi yang dipasarkan'],
        ['no' => 2, 'aspect' => 'T', 'desc' => 'Layanan pemeliharaan produk telah disediakan'],
        ['no' => 3, 'aspect' => 'T', 'desc' => 'Pasokan suku cadang untuk produk teknologi telah disediakan'],
        ['no' => 4, 'aspect' => 'T', 'desc' => 'Adanya aktivitas pengembangan dengan intensitas lebih rendah, untuk peningkatan kerja produk teknologi sesuai permintaan pelanggan'],
        ['no' => 5, 'aspect' => 'M', 'desc' => 'Telah menyediakan pelayanan dan solusi yang lengkap'],
        ['no' => 6, 'aspect' => 'M', 'desc' => 'Telah melakukan diferensiasi produk'],
        ['no' => 7, 'aspect' => 'M', 'desc' => 'Telah melakukan penyempurnaan model bisnis'],
        ['no' => 8, 'aspect' => 'M', 'desc' => 'Telah menggunakan kemitraan untuk berkompetisi di pasar'],
        ['no' => 9, 'aspect' => 'O', 'desc' => 'Telah meningkatkan efektivitas dan kerjasama'],
        ['no' => 10, 'aspect' => 'O', 'desc' => 'Telah melakukan penataan kembali struktur perusahaan sesuai kebutuhan'],
        ['no' => 11, 'aspect' => 'O', 'desc' => 'Identifikasi peningkatan peluang pertemuan produk teknologi dengan kebutuhan pasar'],
        ['no' => 12, 'aspect' => 'O', 'desc' => 'Telah melakukan peninjauan proses teknis dan komersial untuk meningkatkan harga dan keuntungan'],
        ['no' => 13, 'aspect' => 'Mf', 'desc' => 'Menerapkan GMP (Good Manufacturing Practice) atau Lean Manufacturing secara intensif'],
        ['no' => 14, 'aspect' => 'Mf', 'desc' => 'Adanya kebutuhan saran (baik internal maupun eksternal) kepada manajemen untuk perbaikan kinerja'],
        ['no' => 15, 'aspect' => 'Mf', 'desc' => 'Telah menerapkan jaminan mutu sesuai standar'],
        ['no' => 16, 'aspect' => 'Mf', 'desc' => 'Adanya jaminan terhadap mutu, keamanan dan keselamatan produk yang dimanfaatkan oleh masyarakat'],
        ['no' => 17, 'aspect' => 'I', 'desc' => 'Kebutuhan perluasan pasar telah diidentifikasi'],
        ['no' => 18, 'aspect' => 'I', 'desc' => 'Adanya peningkatan kapasitas produksi'],
        ['no' => 19, 'aspect' => 'P', 'desc' => 'Peningkatan kerjasama di dalam jejaring secara dinamis'],
        ['no' => 20, 'aspect' => 'P', 'desc' => 'Telah melakukan peningkatan mutu pengelolaan pada produk yang sudah berjalan'],
        ['no' => 21, 'aspect' => 'P', 'desc' => 'Kerja sama dalam distribusi dan pemasaran produk'],
        ['no' => 22, 'aspect' => 'R', 'desc' => 'Penyusunan rencana pengendalian risiko non teknologi (organisasi dan sosial) pada tahap kematangan pasar tercapai'],
        ['no' => 23, 'aspect' => 'R', 'desc' => 'Kajian risiko organisasi (khususnya indikator keuangan) pada tahap kematangan pasar tercapai'],
        ['no' => 24, 'aspect' => 'R', 'desc' => 'Kajian risiko dampak sosial pada tahap kematangan pasar tercapai'],
    ],
    
    // INDIKATOR 6 - Total 14 rows
    6 => [
        ['no' => 1, 'aspect' => 'T', 'desc' => 'Produk teknologi milik kompetitor telah ditinjau'],
        ['no' => 2, 'aspect' => 'T', 'desc' => 'Telah meninjau kemampuan teknologi yang dimiliki untuk mendukung inovasi ulang atau pengembangan teknologi baru'],
        ['no' => 3, 'aspect' => 'T', 'desc' => 'Telah memilih antara melakukan inovasi ulang produk teknologi yang ada, atau mengembangkan produk teknologi baru'],
        ['no' => 4, 'aspect' => 'M', 'desc' => 'Penurunan pasar telah dikonfirmasi'],
        ['no' => 5, 'aspect' => 'M', 'desc' => 'Riset pasar untuk persetujuan inovasi ulang atau pengembangan teknologi yang lebih maju'],
        ['no' => 6, 'aspect' => 'M', 'desc' => 'Permintaan pasar telah ditinjau'],
        ['no' => 7, 'aspect' => 'M', 'desc' => 'Identifikasi peluang tumbuhnya pasar atau ekspansi pasar baru'],
        ['no' => 8, 'aspect' => 'O', 'desc' => 'Adanya peran jaringan kemitraan dalam mendukung inovasi ulang atau pengembangan teknologi baru'],
        ['no' => 9, 'aspect' => 'O', 'desc' => 'Ada peran jejaring dalam mendukung Inovasi Ulang atau Pengembangan Teknologi Baru'],
        ['no' => 10, 'aspect' => 'Mf', 'desc' => 'Ada kebutuhan dilakukannya inovasi produksi atau pengembangan teknologi produksi baru'],
        ['no' => 11, 'aspect' => 'I', 'desc' => 'Telah mengidentifikasi inovasi lanjutan dari produk, berdasarkan kebutuhan dan permintaan pasar saat ini dan beberapa tahun ke depan'],
        ['no' => 12, 'aspect' => 'P', 'desc' => 'Telah melakukan tinjauan terhadap kemitraan yang sudah berjalan'],
        ['no' => 13, 'aspect' => 'P', 'desc' => 'Telah melakukan pencarian mitra potensial untuk mendukung Inovasi ulang atau Pengembangan Teknologi Baru'],
        ['no' => 14, 'aspect' => 'R', 'desc' => 'Telah melakukan kajian risiko untuk mendukung keputusan Inovasi Ulang atau Pengembangan Teknologi Baru'],
    ],
];
