<?php

return [
    'keywords' => [
        'SDG-1' => ['poverty', 'social protection', 'health insurance', 'social welfare', 'welfare', 'social security', 'pension', 'social policy', 'unemployment', 'social investment', 'safety net', 'social', 'social exclusion', 'inequality', 'insurance', 'retrenchment', 'access', 'developing countries', 'employment', 'poor', 'poverty line', 'uninsured', 'social policies', 'lorenz', 'economic resources', 'income', 'policy', 'water', 'unemployment insurance', 'gini', 'tanf', 'pension plan', 'welfare reform', 'family policy', 'urban', 'economic', 'exclusion', 'telecommunication', 'public pension'],
        'SDG-2' => ['malnutrition', 'biological control', 'food security', 'domestication', 'organic systems', 'stunting', 'agroforestry', 'biocontrol', 'agricultural', 'undernutrition', 'malnourished', 'agriculture', 'smallholder', 'organic', 'natural enemies', 'precision agriculture', 'enemies', 'intercropping', 'precision'],
        'SDG-3' => ['cancer', 'aids', 'stroke', 'diabetes', 'obesity', 'hiv', 'suicide', 'asthma', 'carcinoma', 'tuberculosis', 'malaria', 'hepatitis', 'pneumonia', 'anticancer', 'influenza', 'heart disease', 'leukemia', 'strokes', 'cancers', 'melanoma', 'lymphoma', 'substance abuse', 'environmental health', 'collision', 'diseases', 'mrsa', 'sars', 'dengue', 'epidemic'],
        'SDG-4' => ['trainees', 'apprenticeship', 'professional training', 'educational needs', 'distance learning', 'educational strategies', 'school environment', 'trainee', 'professional education', 'special education', 'education', 'reading', 'academic performance', 'distance education', 'education needs', 'school buildings', 'practical training', 'education reform', 'educational', 'humanistic', 'learning', 'vocational training', 'educational reform', 'distance', 'social responsibility', 'school', 'internship', 'skills', 'citizenship education', 'school attendance', 'school achievement', 'soft skills', 'reading comprehension', 'technical education', 'teaching quality', 'achievement', 'learning activities', 'training', 'education quality'],
        'SDG-5' => ['gender', 'std', 'women', 'sexism', 'feminist', 'aggression', 'marginalized', 'gender issues', 'sexual risk', 'hypersexuality', 'gender gap', 'female', 'gender bias', 'status women', 'misogyny', 'feminist theory', 'condom', 'marginalization', 'feminism', 'transmission', 'paid work', 'gap', 'sexually transmitted', 'hegemonic', 'women rights', 'woman', 'sexual', 'empowerment'],
        'SDG-6' => ['wastewater', 'water management', 'water quality', 'desalination', 'waste water', 'activated sludge', 'water pollution', 'wastewaters', 'water', 'sanitation', 'water treatment', 'contaminated water', 'drinking water', 'wastewater treatment', 'irrigation', 'sewage treatment', 'drinking', 'groundwater', 'restoration', 'effluent', 'contamination', 'polluted water', 'water contamination', 'water supply', 'waste waters', 'effluents', 'water scarcity', 'treatment', 'water saving'],
        'SDG-7' => ['photovoltaic', 'energy efficiency', 'biodiesel', 'internet things', 'biofuel', 'energy efficient', 'fuel cell', 'solar cells', 'hydropower', 'geothermal', 'biofuels', 'fuel cells', 'bioenergy', 'hydroelectric', 'solar', 'renewable energy', 'things', 'iter', 'energy saving', 'hydrogen evolution', 'light emitting', 'bioethanol', 'energy', 'photovoltaics', 'renewable', 'smart grid', 'biomass', 'hydrogen'],
        'SDG-8' => ['human capital', 'labor market', 'labour market', 'crop productivity', 'economic development', 'economic growth', 'occupational safety', 'productivity', 'environmental economic', 'sustainable development', 'soil productivity', 'regional development', 'regional growth', 'economies scale', 'job search', 'industrial policy', 'labor markets', 'climate change', 'technological progress', 'environmental impact', 'self employment', 'technological change', 'development policy', 'financial literacy', 'policy recommendations', 'job insecurity', 'labor', 'tourism', 'young workers'],
        'SDG-9' => ['infrastructure', 'manufacturing', 'internet access', 'industrial', 'microfabrication', 'prototyping', 'industry', 'innovative', 'micromachining', 'nanofabrication', 'mobile users', 'research development', 'rapid prototyping', 'access internet', 'digital divide', 'innovation', 'manufacturing technology', 'infrastructure projects', 'sustainable', 'employment', 'distributed control', 'technological capabilities', 'transport infrastructure', 'machining', 'transportation infrastructure', 'web access', 'cnc', 'new technologies', 'new technology'],
        'SDG-10' => ['medicaid', 'social justice', 'financial crisis', 'social integration', 'social inclusion', 'disparities', 'social mobility', 'health disparities', 'social inequality', 'financial stability', 'social stratification', 'social inequalities', 'inequalities', 'migrant workers', 'health inequalities', 'students autism', 'asylum', 'equal opportunity', 'migration', 'remittances', 'financial crises', 'remittance', 'immigration', 'disparity', 'medicare medicaid', 'economic inequality', 'affirmative action', 'equal', 'financial', 'inclusive', 'health equity', 'inequities', 'racial discrimination', 'discrimination', 'international migration', 'upward mobility', 'undocumented', 'social', 'stratification'],
        'SDG-11' => ['solid waste', 'urban', 'road network', 'earthquake', 'heritage', 'natural disasters', 'urban development', 'public transport', 'intelligent transportation', 'urban planning', 'city', 'public transportation', 'smart cities', 'road networks', 'cultural heritage', 'housing', 'housing market', 'waste', 'municipal', 'flood', 'smart city', 'disaster prevention', 'natural disaster', 'gentrification', 'earthquakes', 'intelligent transport', 'homeownership', 'traffic noise', 'traffic', 'transit', 'disaster', 'flood risk', 'drought monitoring', 'urbanization', 'public space', 'world heritage', 'residential mobility', 'urban land', 'sewage'],
        'SDG-12' => ['recycling', 'recycle', 'composting', 'waste disposal', 'sustainable production', 'vermicompost', 'food preservation', 'waste', 'hazardous waste', 'tourism', 'waste management', 'recycled', 'landfill', 'waste treatment', 'tourism development', 'natural resource', 'environmental attitudes', 'cycle analysis', 'sustainability assessment', 'nuclear waste', 'circular economy', 'sustainable', 'food preservative', 'lca', 'disposal', 'resource management', 'preservative', 'energy performance', 'deinking', 'sustainable building', 'sustainable construction'],
        'SDG-13' => ['climate change', 'co2', 'co2 emissions', 'climate warming', 'greenhouse gas', 'global warming', 'global climate', 'co2 emission', 'warming', 'climate', 'carbon footprint', 'gas emissions', 'emissions', 'carbon dioxide', 'carbon conversion', 'greenhouse gases', 'capture', 'greenhouse', 'ipcc', 'co2 reduction', 'carbon', 'effects climate', 'ghg', 'mitigation', 'carbon capture', 'carbon removal', 'carbon reduction', 'dioxide'],
        'SDG-14' => ['marine', 'oil spill', 'conservation', 'coastal', 'phosphorus removal', 'spill', 'global warming', 'sea', 'emission', 'bloom', 'blooms', 'fisheries management', 'ocean', 'aquaculture', 'hydrocarbons', 'oil spills', 'eutrophication', 'coast', 'contamination', 'pollution', 'overfishing', 'algal blooms', 'contaminants', 'alexandrium', 'oceanic', 'contaminated', 'coastal protection', 'oceans', 'ebpr'],
        'SDG-15' => ['bioremediation', 'extinction', 'conservation', 'phytoremediation', 'invasive', 'endangered', 'afforestation', 'reforestation', 'soil conservation', 'desertification', 'revegetation', 'restoration', 'predator prey', 'endangered species', 'poaching', 'valuation', 'environmental conservation', 'nature conservation', 'invasive weed', 'ecosystem management', 'preservation', 'wildlife', 'phytoextraction', 'invasive species', 'species', 'deforestation', 'species conservation', 'chimpanzees', 'ecological restoration'],
        'SDG-16' => ['human rights', 'corruption', 'community engagement', 'community participation', 'child welfare', 'rule law', 'mafia', 'participatory', 'homicide', 'community involvement', 'public participation', 'participatory research', 'collaborative decision', 'public engagement', 'abuse', 'human right', 'child protection', 'infanticide', 'freedom', 'participatory approach', 'maltreatment', 'armed conflict', 'political participation', 'government', 'corrupt', 'employee involvement', 'cyberbullying', 'armed', 'aggression', 'civic engagement', 'incest', 'physical aggression', 'bullying', 'terrorist', 'assault', 'public involvement', 'violence', 'involvement', 'participation'],
    ],
];
